"""Generate schema-independent runtime clones from the installed CP tables.

SELECT * is intentional: the clone inherits every column at activation time,
including CP fields added since this generator ran. Related tables are selected
from vanilla/CP XML definitions, excluding tables introduced by unrelated mods.
"""
from pathlib import Path
import sqlite3
import xml.etree.ElementTree as ET
from validate_mod import GAME_USER_ROOT, ROOT

GAME = Path("G:/SteamLibrary/steamapps/common/Sid Meier's Civilization V/Assets")
CP = GAME_USER_ROOT / "MODS/(1) Community Patch"


def build():
    known = set()
    for folder in (GAME / "Gameplay/XML", GAME / "DLC/Expansion/Gameplay/XML",
                   GAME / "DLC/Expansion2/Gameplay/XML", CP / "Database Changes"):
        for path in folder.rglob("*.xml"):
            try:
                tree = ET.parse(path)
                known.update(node.get("name") for node in tree.iter("Table") if node.get("name"))
            except ET.ParseError:
                pass
    db = sqlite3.connect(f"file:{(GAME_USER_ROOT/'cache/Civ5DebugDatabase.db').as_posix()}?mode=ro", uri=True)
    tables = {row[0] for row in db.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    lines = ["-- Generated by Tools/build_soft_kitty_inheritance.py.",
             "-- Copies the active CP baseline at mod activation; does not hardcode its values."]
    clones = (("Buildings", "Type", "BUILDING_OPERA_HOUSE", "BUILDING_TRENT_COMFORT_ROOM"),
              ("Units", "Type", "UNIT_MUSICIAN", "UNIT_TRENT_HOPELESS_ROMANTIC"),
              ("Civilizations", "Type", "CIVILIZATION_AMERICA", "CIVILIZATION_TRENT_SOFT_KITTY"),
              ("Leaders", "Type", "LEADER_WASHINGTON", "LEADER_TRENT_SOFT_KITTY"))
    rows = list(clones)
    for table in sorted(known & tables):
        columns = {r[1] for r in db.execute(f'PRAGMA table_info("{table}")')}
        if table.startswith("Building_") and "BuildingType" in columns:
            rows.append((table, "BuildingType", "BUILDING_OPERA_HOUSE", "BUILDING_TRENT_COMFORT_ROOM"))
        if (table.startswith("Unit_") or table == "UnitGameplay2DScripts") and "UnitType" in columns:
            rows.append((table, "UnitType", "UNIT_MUSICIAN", "UNIT_TRENT_HOPELESS_ROMANTIC"))
    for table, column, original, replacement in rows:
        columns = {r[1] for r in db.execute(f'PRAGMA table_info("{table}")')}
        lines += [f'CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "{table}" WHERE {column}=\'{original}\';',
                  f"UPDATE SoftKittyClone SET {column}='{replacement}'" + (", ID=NULL;" if "ID" in columns else ";"),
                  f'INSERT INTO "{table}" SELECT * FROM SoftKittyClone;',
                  'DROP TABLE SoftKittyClone;', '']
    (ROOT / "SQL/70_SoftKitty_Inherit.sql").write_text("\n".join(lines)+"\n", encoding="utf-8")
    print(f"Generated {len(rows)} baseline clones")


if __name__ == "__main__":
    build()
