"""Generate CP-baseline clones for Trent the Phone Stealer.

SELECT * is intentional: the Una Court Butler inherits every Worker column and
related table row from the Community Patch version active at mod activation.
"""
from pathlib import Path
import sqlite3
import xml.etree.ElementTree as ET

from validate_mod import GAME_USER_ROOT, ROOT


GAME = Path("G:/SteamLibrary/steamapps/common/Sid Meier's Civilization V/Assets")
CP = GAME_USER_ROOT / "MODS/(1) Community Patch"


def build():
    known = set()
    for folder in (
        GAME / "Gameplay/XML",
        GAME / "DLC/Expansion/Gameplay/XML",
        GAME / "DLC/Expansion2/Gameplay/XML",
        CP / "Database Changes",
    ):
        for path in folder.rglob("*.xml"):
            try:
                tree = ET.parse(path)
                known.update(node.get("name") for node in tree.iter("Table") if node.get("name"))
            except ET.ParseError:
                pass

    db_path = GAME_USER_ROOT / "cache/Civ5DebugDatabase.db"
    db = sqlite3.connect(f"file:{db_path.as_posix()}?mode=ro", uri=True)
    tables = {row[0] for row in db.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    # This base-game table is created outside the XML table definitions scanned
    # above, but its Worker row is still part of the unit's baseline behavior.
    known.add("UnitGameplay2DScripts")
    rows = [
        ("Units", "Type", "UNIT_WORKER", "UNIT_TRENT_UNA_COURT_BUTLER"),
        ("Civilizations", "Type", "CIVILIZATION_AMERICA", "CIVILIZATION_TRENT_PHONE_STEALER"),
        ("Leaders", "Type", "LEADER_WASHINGTON", "LEADER_TRENT_PHONE_STEALER"),
    ]
    for table in sorted(known & tables):
        columns = {row[1] for row in db.execute(f'PRAGMA table_info("{table}")')}
        if (table.startswith("Unit_") or table == "UnitGameplay2DScripts") and "UnitType" in columns:
            rows.append((table, "UnitType", "UNIT_WORKER", "UNIT_TRENT_UNA_COURT_BUTLER"))

    lines = [
        "-- Generated by Tools/build_phone_stealer_inheritance.py.",
        "-- Copies the active CP Worker baseline at activation; values are not hardcoded.",
    ]
    for table, column, original, replacement in rows:
        columns = {row[1] for row in db.execute(f'PRAGMA table_info("{table}")')}
        lines += [
            f'CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "{table}" WHERE {column}=\'{original}\';',
            f"UPDATE PhoneStealerClone SET {column}='{replacement}'" + (", ID=NULL;" if "ID" in columns else ";"),
            f'INSERT INTO "{table}" SELECT * FROM PhoneStealerClone;',
            "DROP TABLE PhoneStealerClone;",
            "",
        ]
    (ROOT / "SQL/90_PhoneStealer_Inherit.sql").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Generated {len(rows)} Phone Stealer baseline clones")


if __name__ == "__main__":
    build()
