"""Generate CP-baseline clones for the Library Exile civilization.

SELECT * is intentional: the School Library and iPad Reader inherit every
column and related table row from the currently loaded Community Patch.
"""
from pathlib import Path
import sqlite3
import xml.etree.ElementTree as ET
from validate_mod import GAME_USER_ROOT, ROOT

GAME = Path("G:/SteamLibrary/steamapps/common/Sid Meier's Civilization V/Assets")
CP = GAME_USER_ROOT / "MODS/(1) Community Patch"


def build():
    known = set()
    for folder in (GAME / "Gameplay/XML", GAME / "DLC/Expansion/Gameplay/XML",
                   GAME / "DLC/Expansion2/Gameplay/XML", CP / "Database Changes"):
        for path in folder.rglob("*.xml"):
            try:
                tree = ET.parse(path)
                known.update(node.get("name") for node in tree.iter("Table") if node.get("name"))
            except ET.ParseError:
                pass
    db_path = GAME_USER_ROOT / "cache/Civ5DebugDatabase.db"
    db = sqlite3.connect(f"file:{db_path.as_posix()}?mode=ro", uri=True)
    tables = {row[0] for row in db.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    rows = [
        ("Buildings", "Type", "BUILDING_LIBRARY", "BUILDING_TRENT_SCHOOL_LIBRARY"),
        ("Units", "Type", "UNIT_WRITER", "UNIT_TRENT_IPAD_READER"),
        ("Civilizations", "Type", "CIVILIZATION_AMERICA", "CIVILIZATION_TRENT_LIBRARY_EXILE"),
        ("Leaders", "Type", "LEADER_WASHINGTON", "LEADER_TRENT_LIBRARY_EXILE"),
    ]
    for table in sorted(known & tables):
        columns = {row[1] for row in db.execute(f'PRAGMA table_info("{table}")')}
        if table.startswith("Building_") and "BuildingType" in columns:
            rows.append((table, "BuildingType", "BUILDING_LIBRARY", "BUILDING_TRENT_SCHOOL_LIBRARY"))
        if (table.startswith("Unit_") or table == "UnitGameplay2DScripts") and "UnitType" in columns:
            rows.append((table, "UnitType", "UNIT_WRITER", "UNIT_TRENT_IPAD_READER"))
    lines = ["-- Generated by Tools/build_library_exile_inheritance.py.",
             "-- Copies the active CP baseline at activation; values are not hardcoded."]
    for table, column, original, replacement in rows:
        columns = {row[1] for row in db.execute(f'PRAGMA table_info("{table}")')}
        lines += [f'CREATE TEMP TABLE LibraryExileClone AS SELECT * FROM "{table}" WHERE {column}=\'{original}\';',
                  f"UPDATE LibraryExileClone SET {column}='{replacement}'" + (", ID=NULL;" if "ID" in columns else ";"),
                  f'INSERT INTO "{table}" SELECT * FROM LibraryExileClone;',
                  "DROP TABLE LibraryExileClone;", ""]
    (ROOT / "SQL/80_LibraryExile_Inherit.sql").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated {len(rows)} Library Exile baseline clones")


if __name__ == "__main__":
    build()
