"""Generate activation-time clones using installed BNW/CP table definitions."""
from pathlib import Path
import xml.etree.ElementTree as ET
from validate_mod import ROOT, GAME_USER_ROOT
from princedom_db import database


def build():
    known = {"UnitGameplay2DScripts"}
    game = Path("G:/SteamLibrary/steamapps/common/Sid Meier's Civilization V/Assets")
    cp = GAME_USER_ROOT / "MODS/(1) Community Patch"
    for folder in (game / "Gameplay/XML", game / "DLC/Expansion/Gameplay/XML",
                   game / "DLC/Expansion2/Gameplay/XML", cp / "Database Changes"):
        for path in folder.rglob("*.xml"):
            try:
                known.update(n.get("name") for n in ET.parse(path).iter("Table") if n.get("name"))
            except ET.ParseError:
                pass
    db = database()
    rows = [("Civilizations", "Type", "CIVILIZATION_AMERICA", "CIVILIZATION_PRINCE_UNA"),
            ("Leaders", "Type", "LEADER_WASHINGTON", "LEADER_PRINCE_TRENT"),
            ("Units", "Type", "UNIT_WARRIOR", "UNIT_PRINCE_TRENT"),
            ("Units", "Type", "UNIT_WARRIOR", "UNIT_PRINCE_MILITIA"),
            ("Buildings", "Type", "BUILDING_MONUMENT", "BUILDING_PRINCE_FANFIC"),
            ("Buildings", "Type", "BUILDING_MONUMENT", "BUILDING_PRINCE_FANFIC_ACTIVE")]
    # Every intrinsic effect of the baseline Monument is copied. Construction
    # rules, flavors and location prerequisites never belong on its bonus dummy.
    non_effects = {"Building_Flavors", "Building_ClassesNeededInCity", "Building_ClassesNeededNowhere",
                   "Building_ClassesNeededAnywhere", "Building_PrereqBuildingClasses",
                   "Building_ResourceQuantityRequirements", "Building_LocalResourceOrs",
                   "Building_LocalResourceAnds", "Building_TechAndPrereqs"}
    tables = {r[0] for r in db.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    for table in sorted(known & tables):
        cols = {r[1] for r in db.execute(f'PRAGMA table_info("{table}")')}
        if (table.startswith("Unit_") or table == "UnitGameplay2DScripts") and "UnitType" in cols:
            rows.append((table, "UnitType", "UNIT_WARRIOR", "UNIT_PRINCE_TRENT"))
            rows.append((table, "UnitType", "UNIT_WARRIOR", "UNIT_PRINCE_MILITIA"))
        if table.startswith("Building_") and "BuildingType" in cols:
            rows.append((table, "BuildingType", "BUILDING_MONUMENT", "BUILDING_PRINCE_FANFIC"))
            if table not in non_effects:
                rows.append((table, "BuildingType", "BUILDING_MONUMENT", "BUILDING_PRINCE_FANFIC_ACTIVE"))
    lines = ["-- Generated by Tools/build_princedom_inheritance.py.",
             "-- SELECT * reads the active ruleset, including CP-added scalar columns."]
    for table, key, base, clone in rows:
        cols = {r[1] for r in db.execute(f'PRAGMA table_info("{table}")')}
        lines += [f'CREATE TEMP TABLE PrinceClone AS SELECT * FROM "{table}" WHERE {key}=\'{base}\';',
                  f"UPDATE PrinceClone SET {key}='{clone}'" + (", ID=NULL;" if "ID" in cols else ";"),
                  f'INSERT INTO "{table}" SELECT * FROM PrinceClone;', "DROP TABLE PrinceClone;", ""]
    (ROOT / "Princedom/SQL/100_Prince_Inherit.sql").write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {len(rows)} Princedom clones")


if __name__ == "__main__":
    build()
