-- ===========================================================================
-- The Dominion of Una Court - aggressive alternate Trentrouls civilization
-- Centrelink is deliberately not redefined here: both civilizations reference
-- the single BUILDING_UNA_CENTRELINK definition from 00_UnaCourt_Core.sql.
-- ===========================================================================

-- Ask the Community Patch DLL to raise GameEvents.GameSave before it writes
-- the native unit stream. The Lua gameplay layer uses this to return temporary
-- possession bodies to their ordinary owners before any save is serialized.
UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'EVENTS_GAME_SAVE';

INSERT OR REPLACE INTO Colors (Type, Red, Green, Blue, Alpha) VALUES
('COLOR_DOMINION_UNA_PRIMARY',   0.42, 0.04, 0.03, 1.0),
('COLOR_DOMINION_UNA_SECONDARY', 0.95, 0.58, 0.12, 1.0);

INSERT OR REPLACE INTO PlayerColors (Type, PrimaryColor, SecondaryColor, TextColor)
VALUES ('PLAYERCOLOR_DOMINION_UNA', 'COLOR_DOMINION_UNA_PRIMARY',
        'COLOR_DOMINION_UNA_SECONDARY', 'COLOR_PLAYER_WHITE_TEXT');

INSERT INTO Traits (Type, Description, ShortDescription)
VALUES ('TRAIT_DOMINION_ONE_WHO_POSSESSES',
        'TXT_KEY_TRAIT_DOMINION_ONE_WHO_POSSESSES_HELP',
        'TXT_KEY_TRAIT_DOMINION_ONE_WHO_POSSESSES_SHORT');

INSERT INTO Leaders
    (Type, Description, Civilopedia, CivilopediaTag, ArtDefineTag,
     PrimaryVictoryPursuit, SecondaryVictoryPursuit,
     VictoryCompetitiveness, WonderCompetitiveness, MinorCivCompetitiveness,
     Boldness, DiploBalance, WarmongerHate, DoFWillingness, DenounceWillingness,
     WorkWithWillingness, WorkAgainstWillingness, Loyalty, Forgiveness, Neediness,
     Meanness, Chattiness, PortraitIndex, IconAtlas)
SELECT
    'LEADER_DOMINION_TRENTROULS', 'TXT_KEY_LEADER_DOMINION_TRENTROULS',
    'TXT_KEY_LEADER_DOMINION_TRENTROULS_PEDIA', 'TXT_KEY_CIVILOPEDIA_LEADERS_DOMINION_TRENTROULS',
    ArtDefineTag, 'VICTORY_PURSUIT_DOMINATION', 'VICTORY_PURSUIT_DIPLOMACY',
    10, 3, 7, 10, 3, 2, 3, 9, 2, 9, 6, 2, 6, 9, 6,
    0, 'DOMINION_TRENTROULS_UNIT_ATLAS'
FROM Leaders WHERE Type = 'LEADER_WASHINGTON';

INSERT INTO Leader_Traits (LeaderType, TraitType)
VALUES ('LEADER_DOMINION_TRENTROULS', 'TRAIT_DOMINION_ONE_WHO_POSSESSES');

INSERT INTO Leader_MajorCivApproachBiases (LeaderType, MajorCivApproachType, Bias)
SELECT 'LEADER_DOMINION_TRENTROULS', MajorCivApproachType, Bias
FROM Leader_MajorCivApproachBiases WHERE LeaderType = 'LEADER_WASHINGTON';

INSERT INTO Leader_MinorCivApproachBiases (LeaderType, MinorCivApproachType, Bias)
SELECT 'LEADER_DOMINION_TRENTROULS', MinorCivApproachType, Bias
FROM Leader_MinorCivApproachBiases WHERE LeaderType = 'LEADER_WASHINGTON';

INSERT INTO Leader_Flavors (LeaderType, FlavorType, Flavor)
SELECT 'LEADER_DOMINION_TRENTROULS', FlavorType, Flavor
FROM Leader_Flavors WHERE LeaderType = 'LEADER_WASHINGTON';

UPDATE Leader_Flavors SET Flavor = 12
WHERE LeaderType = 'LEADER_DOMINION_TRENTROULS'
  AND FlavorType IN ('FLAVOR_OFFENSE', 'FLAVOR_MOBILE', 'FLAVOR_MILITARY_TRAINING');
UPDATE Leader_Flavors SET Flavor = 9
WHERE LeaderType = 'LEADER_DOMINION_TRENTROULS'
  AND FlavorType IN ('FLAVOR_DEFENSE', 'FLAVOR_EXPANSION', 'FLAVOR_HAPPINESS');

INSERT INTO Civilizations
    (Type, Description, Civilopedia, CivilopediaTag, Strategy, Playable, AIPlayable,
     ShortDescription, Adjective, DefaultPlayerColor, ArtDefineTag, ArtStyleType,
     ArtStyleSuffix, ArtStylePrefix, PortraitIndex, IconAtlas, AlphaIconAtlas,
     MapImage, DawnOfManQuote, DawnOfManImage, DawnOfManAudio, SoundtrackTag)
SELECT
    'CIVILIZATION_DOMINION_UNA_COURT', 'TXT_KEY_CIV_DOMINION_UNA_COURT_DESC',
    'TXT_KEY_CIV_DOMINION_UNA_COURT_PEDIA', 'TXT_KEY_CIV5_DOMINION_UNA_COURT',
    'TXT_KEY_CIV_DOMINION_UNA_COURT_STRATEGY', 1, 1,
    'TXT_KEY_CIV_DOMINION_UNA_COURT_SHORT_DESC', 'TXT_KEY_CIV_DOMINION_UNA_COURT_ADJECTIVE',
    'PLAYERCOLOR_DOMINION_UNA', ArtDefineTag, ArtStyleType, ArtStyleSuffix, ArtStylePrefix,
    0, 'DOMINION_UNA_CIV_ATLAS', 'DOMINION_UNA_CIV_ALPHA_ATLAS', 'Art/DawnOfMan/UnaCourtMap.dds',
    'TXT_KEY_CIV5_DOM_DOMINION_UNA_COURT_TEXT', 'Art/DominionDawnOfMan/DominionDawnOfMan.dds', '', SoundtrackTag
FROM Civilizations WHERE Type = 'CIVILIZATION_AMERICA';

INSERT INTO Civilization_Leaders (CivilizationType, LeaderheadType)
VALUES ('CIVILIZATION_DOMINION_UNA_COURT', 'LEADER_DOMINION_TRENTROULS');

INSERT INTO Civilization_FreeBuildingClasses (CivilizationType, BuildingClassType)
VALUES ('CIVILIZATION_DOMINION_UNA_COURT', 'BUILDINGCLASS_PALACE');

INSERT INTO Civilization_FreeTechs (CivilizationType, TechType)
VALUES ('CIVILIZATION_DOMINION_UNA_COURT', 'TECH_AGRICULTURE');

INSERT INTO Civilization_Start_Region_Priority (CivilizationType, RegionType)
VALUES ('CIVILIZATION_DOMINION_UNA_COURT', 'REGION_GRASS');

INSERT INTO Civilization_CityNames (CivilizationType, CityName) VALUES
('CIVILIZATION_DOMINION_UNA_COURT', 'TXT_KEY_CITY_NAME_UNA_COURT'),
('CIVILIZATION_DOMINION_UNA_COURT', 'TXT_KEY_CITY_NAME_DOMINION_SEIZED_BODY'),
('CIVILIZATION_DOMINION_UNA_COURT', 'TXT_KEY_CITY_NAME_DOMINION_RED_COURT'),
('CIVILIZATION_DOMINION_UNA_COURT', 'TXT_KEY_CITY_NAME_DOMINION_IRON_WILL'),
('CIVILIZATION_DOMINION_UNA_COURT', 'TXT_KEY_CITY_NAME_UNA_CENTRELINK'),
('CIVILIZATION_DOMINION_UNA_COURT', 'TXT_KEY_CITY_NAME_DOMINION_LAST_BODY'),
('CIVILIZATION_DOMINION_UNA_COURT', 'TXT_KEY_CITY_NAME_DOMINION_POSSESSORS_REST'),
('CIVILIZATION_DOMINION_UNA_COURT', 'TXT_KEY_CITY_NAME_DOMINION_CONQUEST');

INSERT INTO Civilization_SpyNames (CivilizationType, SpyName) VALUES
('CIVILIZATION_DOMINION_UNA_COURT', 'TXT_KEY_SPY_NAME_DOMINION_VESSEL'),
('CIVILIZATION_DOMINION_UNA_COURT', 'TXT_KEY_SPY_NAME_DOMINION_WITNESS'),
('CIVILIZATION_DOMINION_UNA_COURT', 'TXT_KEY_SPY_NAME_DOMINION_USURPER');

-- Dominion-specific promotions never overlap the Freehold's possession state.
INSERT INTO UnitPromotions
    (Type, Description, Help, CannotBeChosen, LostWithUpgrade, CannotBeCaptured,
     NoSupply, CombatPercent, MovesChange, PortraitIndex, IconAtlas, PediaType,
     PediaEntry, Sound, ShowInUnitPanel, IsVisibleAboveFlag)
VALUES
('PROMOTION_DOMINION_ONE_TRUE_RULER', 'TXT_KEY_PROMOTION_DOMINION_ONE_TRUE_RULER',
 'TXT_KEY_PROMOTION_DOMINION_ONE_TRUE_RULER_HELP', 1, 0, 1, 1, 0, 0,
 59, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DOMINION_ONE_TRUE_RULER', 'AS2D_IF_LEVELUP', 1, 1),
('PROMOTION_DOMINION_BORROWED_BODY', 'TXT_KEY_PROMOTION_DOMINION_BORROWED_BODY',
 'TXT_KEY_PROMOTION_DOMINION_BORROWED_BODY_HELP', 1, 0, 1, 1, 5, 0,
 58, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DOMINION_BORROWED_BODY', 'AS2D_IF_LEVELUP', 1, 1),
('PROMOTION_DOMINION_ENEMY_IN_TRENT', 'TXT_KEY_PROMOTION_DOMINION_ENEMY_IN_TRENT',
 'TXT_KEY_PROMOTION_DOMINION_ENEMY_IN_TRENT_HELP', 1, 0, 1, 1, 0, -1,
 58, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DOMINION_ENEMY_IN_TRENT', 'AS2D_IF_LEVELUP', 1, 1),
('PROMOTION_DOMINION_SWAP_READY', 'TXT_KEY_PROMOTION_DOMINION_SWAP_READY',
 'TXT_KEY_PROMOTION_DOMINION_SWAP_READY_HELP', 1, 0, 0, 0, 0, 0,
 58, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DOMINION_SWAP_READY', 'AS2D_IF_LEVELUP', 1, 1),
('PROMOTION_DOMINION_SWAP_COOLDOWN', 'TXT_KEY_PROMOTION_DOMINION_SWAP_COOLDOWN',
 'TXT_KEY_PROMOTION_DOMINION_SWAP_COOLDOWN_HELP', 1, 0, 0, 0, 0, 0,
 58, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DOMINION_SWAP_COOLDOWN', 'AS2D_IF_LEVELUP', 1, 1),
('PROMOTION_DOMINION_SWAP_IMMUNE', 'TXT_KEY_PROMOTION_DOMINION_SWAP_IMMUNE',
 'TXT_KEY_PROMOTION_DOMINION_SWAP_IMMUNE_HELP', 1, 0, 1, 0, 0, 0,
 58, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DOMINION_SWAP_IMMUNE', 'AS2D_IF_LEVELUP', 0, 0);

-- Strength 8/10/16/22/30/42/56/72 from a base strength of 8.
INSERT INTO UnitPromotions
    (Type, Description, Help, CannotBeChosen, LostWithUpgrade, CombatPercent,
     PortraitIndex, IconAtlas, PediaType, PediaEntry, ShowInUnitPanel)
VALUES
('PROMOTION_DOMINION_ERA_ANCIENT',     'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH_HELP', 1, 0,   0, 59, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 0),
('PROMOTION_DOMINION_ERA_CLASSICAL',   'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH_HELP', 1, 0,  25, 59, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 0),
('PROMOTION_DOMINION_ERA_MEDIEVAL',    'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH_HELP', 1, 0, 100, 59, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 0),
('PROMOTION_DOMINION_ERA_RENAISSANCE', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH_HELP', 1, 0, 175, 59, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 0),
('PROMOTION_DOMINION_ERA_INDUSTRIAL',  'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH_HELP', 1, 0, 275, 59, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 0),
('PROMOTION_DOMINION_ERA_MODERN',      'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH_HELP', 1, 0, 425, 59, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 0),
('PROMOTION_DOMINION_ERA_ATOMIC',      'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH_HELP', 1, 0, 600, 59, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 0),
('PROMOTION_DOMINION_ERA_INFORMATION', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH_HELP', 1, 0, 800, 59, 'ABILITY_ATLAS', 'PEDIA_SHARED', 'TXT_KEY_PROMOTION_DOMINION_ERA_STRENGTH', 0);

-- A Warrior-class replacement shown on the selection screen, but with no cost,
-- prerequisite, upgrade route, ruin-upgrade class, or embark capability.
INSERT INTO Units
    (Type, Description, Civilopedia, Strategy, Help, Combat, Cost, FaithCost,
     RequiresFaithPurchaseEnabled, Moves, BaseSightRange, Class, CombatClass, Domain,
     DefaultUnitAI, MilitarySupport, MilitaryProduction, Pillage, PrereqTech,
     ObsoleteTech, GoodyHutUpgradeUnitClass, HurryCostModifier, ExtraMaintenanceCost,
     UnitArtInfo, UnitArtInfoCulturalVariation, UnitArtInfoEraVariation,
     UnitFlagIconOffset, PortraitIndex, IconAtlas, UnitFlagAtlas, ShowInPedia, NoSupply,
     CannotEmbark)
SELECT
    'UNIT_DOMINION_TRENTROULS', 'TXT_KEY_UNIT_DOMINION_TRENTROULS',
    'TXT_KEY_UNIT_DOMINION_TRENTROULS_PEDIA', 'TXT_KEY_UNIT_DOMINION_TRENTROULS_STRATEGY',
    'TXT_KEY_UNIT_DOMINION_TRENTROULS_HELP', 8, -1, -1, 0, 2, 2,
    'UNITCLASS_WARRIOR', CombatClass, Domain, DefaultUnitAI,
    1, 1, 1, NULL, NULL, NULL, -1, 0,
    UnitArtInfo, UnitArtInfoCulturalVariation, UnitArtInfoEraVariation,
    UnitFlagIconOffset, 0, 'DOMINION_TRENTROULS_UNIT_ATLAS', UnitFlagAtlas, 1, 1, 1
FROM Units WHERE Type = 'UNIT_WARRIOR';

INSERT INTO Unit_AITypes (UnitType, UnitAIType)
VALUES ('UNIT_DOMINION_TRENTROULS', 'UNITAI_ATTACK');

INSERT INTO Unit_Flavors (UnitType, FlavorType, Flavor) VALUES
('UNIT_DOMINION_TRENTROULS', 'FLAVOR_OFFENSE', 22),
('UNIT_DOMINION_TRENTROULS', 'FLAVOR_DEFENSE', 18),
('UNIT_DOMINION_TRENTROULS', 'FLAVOR_MOBILE', 16);

INSERT INTO Unit_FreePromotions (UnitType, PromotionType) VALUES
('UNIT_DOMINION_TRENTROULS', 'PROMOTION_DOMINION_ONE_TRUE_RULER'),
('UNIT_DOMINION_TRENTROULS', 'PROMOTION_DOMINION_ERA_ANCIENT'),
('UNIT_DOMINION_TRENTROULS', 'PROMOTION_DOMINION_SWAP_READY');

INSERT INTO Civilization_UnitClassOverrides (CivilizationType, UnitClassType, UnitType)
VALUES ('CIVILIZATION_DOMINION_UNA_COURT', 'UNITCLASS_WARRIOR', 'UNIT_DOMINION_TRENTROULS');

INSERT INTO Civilization_FreeUnits (CivilizationType, UnitClassType, UnitAIType, Count) VALUES
('CIVILIZATION_DOMINION_UNA_COURT', 'UNITCLASS_SETTLER', 'UNITAI_SETTLE', 1),
('CIVILIZATION_DOMINION_UNA_COURT', 'UNITCLASS_WARRIOR', 'UNITAI_ATTACK', 1);

-- Shared unique building: this is only a second override, not a second building.
INSERT INTO Civilization_BuildingClassOverrides (CivilizationType, BuildingClassType, BuildingType)
VALUES ('CIVILIZATION_DOMINION_UNA_COURT', 'BUILDINGCLASS_BANK', 'BUILDING_UNA_CENTRELINK');
