-- English localization for Trentrouls, the Ultimate Possessor.

INSERT OR REPLACE INTO Language_en_US (Tag, Text) VALUES
('TXT_KEY_TRAIT_ULTIMATE_TWO_POSSESSIONS_SHORT', 'Two Possessions for the Price of One'),
('TXT_KEY_TRAIT_ULTIMATE_TWO_POSSESSIONS_HELP', 'May temporarily possess several enemy or Barbarian units near your military units and cities. Maximum targets increase from 1 in the Ancient Era to 8 in the Information Era. Possessing more units creates a longer cooldown.'),

('TXT_KEY_LEADER_ULTIMATE_TRENTROULS', 'Trentrouls'),
('TXT_KEY_LEADER_ULTIMATE_TRENTROULS_PEDIA', 'Trentrouls, Ultimate Possessor of Una Court, does not ask why he should have one army when the world already contains so many perfectly good ones. His authority reaches through nearby soldiers and cities, allowing him to borrow entire enemy formations before returning the survivors to their former masters.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS', 'Trentrouls, the Ultimate Possessor'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS_NAME', 'Trentrouls'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS_SUBTITLE', 'The Ultimate Possessor'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS_LIVED', 'The Age of Many Bodies'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS_TITLES_1', 'Supreme Possessor of Una Court'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS_HEADING_1', 'The Possessor Ascendant'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS_TEXT_1', 'In this telling of Una Court, Trentrouls no longer binds his survival to a single body on the battlefield. He rules from the centre of a widening military network, reaching through every loyal city and soldier to seize whatever vessels the moment requires.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS_HEADING_2', 'Rule by Borrowed Hands'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS_TEXT_2', 'Trentrouls treats an enemy army as an inventory rather than an obstacle. The Court may temporarily command several hostile or Barbarian units at once, turning a carefully staged confrontation into a sudden reversal. The stolen bodies eventually return, but the damage they inflict belongs entirely to Una Court.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS_HEADING_3', 'The Loyal Court'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS_TEXT_3', 'Golden Retrievers range beside the armies of the Court, strengthening nearby soldiers and helping them recover. Centrelink steadies the realm with wealth and local contentment, while the great house at 3 Una Court turns imperial prosperity into something felt in every city.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS_HEADING_4', 'Legacy'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS_TEXT_4', 'The Ultimate Possessor leaves behind a simple doctrine: numbers matter less than access. An army stationed carelessly near Una Court may discover that its strength, weapons and experience have all become Trentrouls'' property for the next few turns.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS_FACT_1', 'Unlike the Freehold and Dominion incarnations, the Ultimate Possessor does not appear as an irreplaceable map unit.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_ULTIMATE_TRENTROULS_FACT_2', 'His possession capacity grows by one with each Era, reaching eight targets in the Information Era.'),

('TXT_KEY_CIV_ULTIMATE_POSSESSION_DESC', 'Trentrouls - Ultimate Possession'),
('TXT_KEY_CIV_ULTIMATE_POSSESSION_SHORT_DESC', 'Ultimate Possession'),
('TXT_KEY_CIV_ULTIMATE_POSSESSION_ADJECTIVE', 'Ultimate'),
('TXT_KEY_CIV_ULTIMATE_POSSESSION_PEDIA', 'From Una Court, Trentrouls reaches across the ages and takes what is his. The Ultimate Possession turns nearby enemy armies into temporary instruments of the Court, supported by loyal Golden Retrievers and the institutions of Centrelink and 3 Una Court.'),
('TXT_KEY_CIV5_ULTIMATE_POSSESSION', 'Ultimate Possession'),
('TXT_KEY_CIV5_ULTIMATE_POSSESSION_HEADING_1', 'Overview'),
('TXT_KEY_CIV5_ULTIMATE_POSSESSION_TEXT_1', 'Ultimate Possession is the army-stealing incarnation of Una Court. It begins with a normal Settler and Warrior rather than a Trentrouls hero unit. Every friendly city and military unit projects a two-tile possession network, allowing the Court to reach hostile formations without risking its leader on the map.'),
('TXT_KEY_CIV5_ULTIMATE_POSSESSION_HEADING_2', 'Two Possessions for the Price of One'),
('TXT_KEY_CIV5_ULTIMATE_POSSESSION_TEXT_2', 'Open the Una Court command panel to select eligible enemy or Barbarian military units inside the network. Capacity begins at one target in the Ancient Era and rises by one each Era, reaching eight in the Information Era. On Standard speed, groups of one to four are possessed for 2 turns, while groups of five to eight are possessed for 1 turn. Cooldown is 8 turns for one unit and increases by 5 turns for every additional unit selected. Possessed units cannot be deleted, gifted or upgraded and surviving units return to their original owners when the effect ends.'),
('TXT_KEY_CIV5_ULTIMATE_POSSESSION_HEADING_3', 'Golden Retriever'),
('TXT_KEY_CIV5_ULTIMATE_POSSESSION_TEXT_3', 'The Golden Retriever replaces the Scout. It costs 45 [ICON_PRODUCTION] Production, moves 3 tiles and carries one additional point of maintenance. Its non-stacking Good Boy aura grants adjacent friendly units +10% [ICON_STRENGTH] Combat Strength and +5 HP healing per turn, making it an effective companion for a concentrated field army.'),
('TXT_KEY_CIV5_ULTIMATE_POSSESSION_HEADING_4', 'Institutions of Una Court'),
('TXT_KEY_CIV5_ULTIMATE_POSSESSION_TEXT_4', 'Centrelink replaces the Bank, retaining its normal economic benefits while adding +1 local [ICON_HAPPINESS_1] Happiness. The unique National Wonder 3 Una Court becomes available at Civil Service for 250 [ICON_PRODUCTION] Production. Once built, every city gains +1 [ICON_HAPPINESS_1] Happiness and +5% [ICON_GOLD] Gold, while unemployed Citizens produce +1 [ICON_CULTURE] Culture.'),
('TXT_KEY_CIV5_ULTIMATE_POSSESSION_HEADING_5', 'Strategy'),
('TXT_KEY_CIV5_ULTIMATE_POSSESSION_TEXT_5', 'Build a broad military network before activating possession. Cities provide dependable anchors, while fast units can extend the network toward artillery, mounted units or other valuable targets. A small possession is available again quickly; a mass seizure can decide a war but creates a much longer cooldown. Golden Retrievers are most effective beside the compact army that will exploit the stolen units.'),
('TXT_KEY_CIV5_ULTIMATE_POSSESSION_FACTOID_HEADING', 'Court Record'),
('TXT_KEY_CIV5_ULTIMATE_POSSESSION_FACTOID_TEXT', 'Ultimate Possession is the only Una Court civilization whose Trentrouls rules entirely through the civilization ability instead of appearing as a unique battlefield unit.'),
('TXT_KEY_CIV_ULTIMATE_POSSESSION_STRATEGY', 'Ultimate Possession rewards careful staging. Place military units and cities near valuable enemy formations, then use the Una Court command panel to seize up to your current Era capacity at once. A larger group creates a longer cooldown, so take only the bodies you can exploit. Golden Retrievers keep a battle group moving and fighting, while Centrelink and 3 Una Court stabilize and enrich a broad empire.'),
('TXT_KEY_CIV5_DOM_ULTIMATE_POSSESSION_TEXT', 'Trentrouls, Ultimate Possessor of Una Court, the world arrives at your throne already full of armies waiting to be borrowed. Your reach grows with every age, from a single uncertain vessel to whole formations bent to your will. Let Golden Retrievers guard your soldiers, let Centrelink steady your cities, and raise 3 Una Court as the heart of your dominion. Why have one army, when you can have yours too?'),

('TXT_KEY_UNIT_ULTIMATE_GOLDEN_RETRIEVER', 'Golden Retriever'),
('TXT_KEY_UNIT_ULTIMATE_GOLDEN_RETRIEVER_HELP', 'Replaces the Scout. Costs more [ICON_PRODUCTION] Production and maintenance, but has +1 [ICON_MOVES] Movement. Good Boy grants adjacent friendly units +10% [ICON_STRENGTH] Combat Strength and +5 HP healing per turn. This aura does not stack.'),
('TXT_KEY_UNIT_ULTIMATE_GOLDEN_RETRIEVER_STRATEGY', 'The Golden Retriever is a fast reconnaissance and support unit. Keep it adjacent to a concentrated battle group to improve both combat strength and recovery. Multiple Golden Retrievers do not stack Good Boy.'),
('TXT_KEY_UNIT_ULTIMATE_GOLDEN_RETRIEVER_PEDIA', 'Una Court has always understood that an army needs loyalty as much as steel. The Golden Retriever ranges ahead like a Scout, then stays close to the soldiers who need the encouragement of a very good boy.[NEWLINE][NEWLINE]In battle, the Retriever is a support piece rather than a front-line fighter. Its Good Boy aura strengthens and heals adjacent friendly units, but multiple Retrievers do not stack the effect. Keep one beside the formation that matters most.'),

('TXT_KEY_PROMOTION_ULTIMATE_GOOD_BOY', 'Good Boy'),
('TXT_KEY_PROMOTION_ULTIMATE_GOOD_BOY_HELP', 'Adjacent friendly units receive +10% [ICON_STRENGTH] Combat Strength and +5 HP healing per turn. This bonus does not stack.'),
('TXT_KEY_PROMOTION_ULTIMATE_GOOD_BOY_AURA', 'Good Boy'),
('TXT_KEY_PROMOTION_ULTIMATE_GOOD_BOY_AURA_HELP', '+10% [ICON_STRENGTH] Combat Strength and +5 HP healing per turn from an adjacent Golden Retriever. This bonus does not stack.'),
('TXT_KEY_PROMOTION_ULTIMATE_POSSESSED', 'Mass Possession'),
('TXT_KEY_PROMOTION_ULTIMATE_POSSESSED_HELP', 'Temporarily controlled by Trentrouls. This unit cannot be deleted, gifted, or upgraded. If it survives, it returns to its original owner when possession ends.'),

('TXT_KEY_BUILDING_ULTIMATE_3_UNA_COURT', '3 Una Court'),
('TXT_KEY_BUILDING_ULTIMATE_3_UNA_COURT_HELP', 'Unique National Wonder. Provides +1 [ICON_HAPPINESS_1] Happiness in every City and +5% [ICON_GOLD] Gold in every City. Unemployed Citizens in every City produce +1 [ICON_CULTURE] Culture.'),
('TXT_KEY_BUILDING_ULTIMATE_3_UNA_COURT_STRATEGY', '3 Una Court is a powerful empire-wide National Wonder. Build it when expansion has created enough cities and unemployed population to benefit from its Happiness, Gold, and Culture.'),
('TXT_KEY_BUILDING_ULTIMATE_3_UNA_COURT_PEDIA', 'The grand house at 3 Una Court is less a residence than the fixed point around which a court of borrowed minds revolves. Its gold-and-purple halls promise prosperity, composure, and something useful for every otherwise idle citizen to do.[NEWLINE][NEWLINE]As a unique National Wonder, 3 Una Court may be built only once. Its influence is empire-wide: every city receives Happiness and a Gold bonus, while unemployed Citizens gain a small source of Culture. This makes the estate especially valuable to a wide empire managing rapid expansion.'),

('TXT_KEY_CITY_NAME_ULTIMATE_UNA_COURT', 'Una Court'),
('TXT_KEY_CITY_NAME_ULTIMATE_PURPLE_COURT', 'Purple Court'),
('TXT_KEY_CITY_NAME_ULTIMATE_MANY_BODIES', 'Many Bodies'),
('TXT_KEY_CITY_NAME_ULTIMATE_GOLDEN_HALL', 'Golden Hall'),
('TXT_KEY_CITY_NAME_ULTIMATE_CENTRELINK', 'Centrelink'),
('TXT_KEY_CITY_NAME_ULTIMATE_GOOD_BOY', 'Good Boy Crossing'),
('TXT_KEY_CITY_NAME_ULTIMATE_THRONE', 'Possessor''s Throne'),
('TXT_KEY_CITY_NAME_ULTIMATE_LAST_WILL', 'The Last Will'),

('TXT_KEY_SPY_NAME_ULTIMATE_VESSEL', 'The Vessel'),
('TXT_KEY_SPY_NAME_ULTIMATE_HANDLER', 'The Handler'),
('TXT_KEY_SPY_NAME_ULTIMATE_GOOD_BOY', 'Good Boy');
