-- Generated by Tools/build_soft_kitty_inheritance.py.
-- Copies the active CP baseline at mod activation; does not hardcode its values.
CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Buildings" WHERE Type='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET Type='BUILDING_TRENT_COMFORT_ROOM', ID=NULL;
INSERT INTO "Buildings" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Units" WHERE Type='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET Type='UNIT_TRENT_HOPELESS_ROMANTIC', ID=NULL;
INSERT INTO "Units" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Civilizations" WHERE Type='CIVILIZATION_AMERICA';
UPDATE SoftKittyClone SET Type='CIVILIZATION_TRENT_SOFT_KITTY', ID=NULL;
INSERT INTO "Civilizations" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Leaders" WHERE Type='LEADER_WASHINGTON';
UPDATE SoftKittyClone SET Type='LEADER_TRENT_SOFT_KITTY', ID=NULL;
INSERT INTO "Leaders" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_AreaYieldModifiers" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_AreaYieldModifiers" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_BonusFromAccomplishments" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_BonusFromAccomplishments" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_BuildingClassHappiness" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_BuildingClassHappiness" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_BuildingClassLocalHappiness" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_BuildingClassLocalHappiness" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_BuildingClassLocalYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_BuildingClassLocalYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_BuildingClassYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_BuildingClassYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_BuildingClassYieldModifiers" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_BuildingClassYieldModifiers" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_CityConnectionPlotYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_CityConnectionPlotYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_CityConnectionPlotYieldChangesGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_CityConnectionPlotYieldChangesGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ClassNeededAnywhere" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ClassNeededAnywhere" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ClassNeededNowhere" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ClassNeededNowhere" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ClassesNeededInCity" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ClassesNeededInCity" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_DomainFreeExperiencePerGreatWork" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_DomainFreeExperiencePerGreatWork" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_DomainFreeExperiencePerGreatWorkCity" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_DomainFreeExperiencePerGreatWorkCity" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_DomainFreeExperiencePerGreatWorkGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_DomainFreeExperiencePerGreatWorkGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_DomainFreeExperiences" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_DomainFreeExperiences" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_DomainFreeExperiencesGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_DomainFreeExperiencesGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_DomainProductionModifiers" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_DomainProductionModifiers" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ExtraPlayerInstancesFromAccomplishments" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ExtraPlayerInstancesFromAccomplishments" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_FeatureYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_FeatureYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_Flavors" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_Flavors" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_FreeSpecUnits" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_FreeSpecUnits" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_FreeSpecialistCounts" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_FreeSpecialistCounts" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_FreeUnits" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_FreeUnits" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_GlobalYieldModifiers" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_GlobalYieldModifiers" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_GoldenAgeYieldMod" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_GoldenAgeYieldMod" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_GreatPersonPointFromConstruction" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_GreatPersonPointFromConstruction" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_GreatPersonProgressFromConstruction" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_GreatPersonProgressFromConstruction" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_GreatWorkYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_GreatWorkYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_GreatWorkYieldChangesLocal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_GreatWorkYieldChangesLocal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_GrowthExtraYield" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_GrowthExtraYield" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_HurryModifiers" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_HurryModifiers" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_HurryModifiersLocal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_HurryModifiersLocal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ImprovementYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ImprovementYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ImprovementYieldChangesGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ImprovementYieldChangesGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_InstantYield" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_InstantYield" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_InstantYieldFromWLTKDStart" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_InstantYieldFromWLTKDStart" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_LakePlotYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_LakePlotYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_LakePlotYieldChangesGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_LakePlotYieldChangesGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_LocalFeatureAnds" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_LocalFeatureAnds" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_LocalFeatureOrs" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_LocalFeatureOrs" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_LocalResourceAnds" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_LocalResourceAnds" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_LocalResourceOrs" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_LocalResourceOrs" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_LockedBuildingClasses" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_LockedBuildingClasses" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_LuxuryYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_LuxuryYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_PlotYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_PlotYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_PrereqBuildingClasses" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_PrereqBuildingClasses" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ReligionYieldFromFaithPurchasableBuildings" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ReligionYieldFromFaithPurchasableBuildings" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ReligionYieldFromFaithPurchasableBuildingsGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ReligionYieldFromFaithPurchasableBuildingsGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ResourceClaim" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ResourceClaim" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ResourceCultureChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ResourceCultureChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ResourceFaithChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ResourceFaithChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ResourceHappinessChange" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ResourceHappinessChange" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ResourceMonopolyAnds" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ResourceMonopolyAnds" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ResourceMonopolyOrs" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ResourceMonopolyOrs" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ResourcePlotsToPlace" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ResourcePlotsToPlace" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ResourceQuantity" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ResourceQuantity" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ResourceQuantityFromPOP" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ResourceQuantityFromPOP" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ResourceQuantityPerXFranchises" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ResourceQuantityPerXFranchises" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ResourceQuantityRequirements" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ResourceQuantityRequirements" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ResourceYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ResourceYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ResourceYieldChangesGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ResourceYieldChangesGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ResourceYieldModifiers" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ResourceYieldModifiers" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_RiverPlotYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_RiverPlotYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_SeaPlotYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_SeaPlotYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_SeaResourceYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_SeaResourceYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_SpecialistYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_SpecialistYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_SpecialistYieldChangesLocal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_SpecialistYieldChangesLocal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_SpecificGreatPersonRateModifier" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_SpecificGreatPersonRateModifier" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_TechAndPrereqs" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_TechAndPrereqs" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_TechEnhancedYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_TechEnhancedYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_TerrainYieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_TerrainYieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ThemingBonuses" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ThemingBonuses" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_ThemingYieldBonus" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_ThemingYieldBonus" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_UnitClassTrainingAllowed" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_UnitClassTrainingAllowed" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_UnitCombatFreeExperiences" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_UnitCombatFreeExperiences" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_UnitCombatProductionModifiers" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_UnitCombatProductionModifiers" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_UnitCombatProductionModifiersGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_UnitCombatProductionModifiersGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_WLTKDFromProject" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_WLTKDFromProject" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_WLTKDYieldMod" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_WLTKDYieldMod" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangeWorldWonder" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangeWorldWonder" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangeWorldWonderGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangeWorldWonderGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChanges" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChanges" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangesEraScalingTimes100" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangesEraScalingTimes100" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangesFromAccomplishments" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangesFromAccomplishments" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangesFromPassingTR" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangesFromPassingTR" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangesFromXCityStateStrategicResource" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangesFromXCityStateStrategicResource" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangesPerCityStrengthTimes100" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangesPerCityStrengthTimes100" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangesPerGoldenAge" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangesPerGoldenAge" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangesPerLocalTheme" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangesPerLocalTheme" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangesPerMonopoly" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangesPerMonopoly" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangesPerPop" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangesPerPop" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangesPerPopInEmpire" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangesPerPopInEmpire" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangesPerReligion" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangesPerReligion" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangesPerXBuilding" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangesPerXBuilding" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldChangesPerXTiles" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldChangesPerXTiles" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromBirth" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromBirth" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromBirthRetroactive" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromBirthRetroactive" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromBorderGrowth" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromBorderGrowth" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromCombatExperienceTimes100" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromCombatExperienceTimes100" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromConstruction" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromConstruction" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromDeath" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromDeath" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromFaithPurchase" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromFaithPurchase" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromGPBirthScaledWithArtistBulb" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromGPBirthScaledWithArtistBulb" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromGPBirthScaledWithPerTurnYield" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromGPBirthScaledWithPerTurnYield" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromGPBirthScaledWithWriterBulb" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromGPBirthScaledWithWriterBulb" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromGPExpend" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromGPExpend" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromGoldenAgeStart" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromGoldenAgeStart" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromInternalTR" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromInternalTR" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromInternalTREnd" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromInternalTREnd" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromInternationalTREnd" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromInternationalTREnd" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromLongCount" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromLongCount" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromPillage" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromPillage" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromPillageGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromPillageGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromPillageGlobalPlayer" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromPillageGlobalPlayer" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromPolicyUnlock" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromPolicyUnlock" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromProcessModifier" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromProcessModifier" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromPurchase" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromPurchase" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromPurchaseGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromPurchaseGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromSpyAttack" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromSpyAttack" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromSpyDefense" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromSpyDefense" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromSpyDefenseOrID" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromSpyDefenseOrID" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromSpyIdentify" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromSpyIdentify" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromSpyRigElection" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromSpyRigElection" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromTech" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromTech" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromUnitGiftGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromUnitGiftGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromUnitLevelUp" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromUnitLevelUp" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromUnitLevelUpGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromUnitLevelUpGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromUnitProduction" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromUnitProduction" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromVictory" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromVictory" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromVictoryGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromVictoryGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromVictoryGlobalPlayer" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromVictoryGlobalPlayer" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromYieldPercent" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromYieldPercent" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldFromYieldPercentGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldFromYieldPercentGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldModifiers" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldModifiers" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldModifiersEraScaling" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldModifiersEraScaling" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldModifiersFromAccomplishments" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldModifiersFromAccomplishments" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldModifiersFromDistanceToCapital" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldModifiersFromDistanceToCapital" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldPerAllyTimes100" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldPerAllyTimes100" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldPerFranchise" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldPerFranchise" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldPerFriendTimes100" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldPerFriendTimes100" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldPerXFeatureTimes100" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldPerXFeatureTimes100" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldPerXImprovementGlobal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldPerXImprovementGlobal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldPerXImprovementLocal" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldPerXImprovementLocal" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Building_YieldPerXTerrainTimes100" WHERE BuildingType='BUILDING_OPERA_HOUSE';
UPDATE SoftKittyClone SET BuildingType='BUILDING_TRENT_COMFORT_ROOM';
INSERT INTO "Building_YieldPerXTerrainTimes100" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_AITypes" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_AITypes" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_Bounties" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_Bounties" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_BuildOnFound" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_BuildOnFound" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_BuildingClassPurchaseRequireds" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_BuildingClassPurchaseRequireds" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_BuildingClassRequireds" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_BuildingClassRequireds" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_Buildings" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_Buildings" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_Builds" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_Builds" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_ClassUpgrades" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_ClassUpgrades" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_EraCombatStrength" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_EraCombatStrength" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_EraCombatType" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_EraCombatType" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_EraUnitPromotions" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_EraUnitPromotions" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_Flavors" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_Flavors" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_FreePromotions" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_FreePromotions" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_GreatPersons" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_GreatPersons" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_NotAITypes" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_NotAITypes" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_ProductionModifierBuildings" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_ProductionModifierBuildings" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_ProductionTraits" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_ProductionTraits" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_ResourceQuantityExpended" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_ResourceQuantityExpended" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_ResourceQuantityRequirements" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_ResourceQuantityRequirements" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_ResourceQuantityTotals" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_ResourceQuantityTotals" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_ScalingFromOwnedImprovements" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_ScalingFromOwnedImprovements" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_TechTypes" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_TechTypes" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_UniqueNames" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_UniqueNames" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_YieldFromBarbarianKills" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_YieldFromBarbarianKills" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_YieldFromKills" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_YieldFromKills" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

CREATE TEMP TABLE SoftKittyClone AS SELECT * FROM "Unit_YieldOnCompletion" WHERE UnitType='UNIT_MUSICIAN';
UPDATE SoftKittyClone SET UnitType='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO "Unit_YieldOnCompletion" SELECT * FROM SoftKittyClone;
DROP TABLE SoftKittyClone;

