-- Soft Kitty Serenader: modifiers layered onto the currently loaded CP baseline.
UPDATE CustomModOptions SET Value=1 WHERE Name IN
('EVENTS_CITY', 'EVENTS_UNIT_CREATED', 'EVENTS_UNIT_UPGRADES', 'EVENTS_UNIT_CAPTURE');

INSERT INTO Colors (Type,Red,Green,Blue,Alpha) VALUES
('COLOR_TRENT_SOFT_KITTY_NAVY',0.055,0.10,0.22,1),
('COLOR_TRENT_SOFT_KITTY_GOLD',0.94,0.74,0.33,1);
INSERT INTO PlayerColors (Type,PrimaryColor,SecondaryColor,TextColor) VALUES
('PLAYERCOLOR_TRENT_SOFT_KITTY','COLOR_TRENT_SOFT_KITTY_NAVY','COLOR_TRENT_SOFT_KITTY_GOLD','COLOR_PLAYER_WHITE_TEXT');
INSERT INTO Traits (Type,Description,ShortDescription) VALUES
('TRAIT_TRENT_SOFT_KITTY','TXT_KEY_SOFT_KITTY_TRAIT_HELP','TXT_KEY_SOFT_KITTY_TRAIT');

UPDATE Civilizations SET Description='TXT_KEY_SOFT_KITTY_CIV', ShortDescription='TXT_KEY_SOFT_KITTY_SHORT',
Adjective='TXT_KEY_SOFT_KITTY_ADJECTIVE', Civilopedia='TXT_KEY_SOFT_KITTY_PEDIA',
CivilopediaTag='TXT_KEY_CIV5_SOFT_KITTY', Strategy='TXT_KEY_SOFT_KITTY_STRATEGY', Playable=1, AIPlayable=1,
DefaultPlayerColor='PLAYERCOLOR_TRENT_SOFT_KITTY', PortraitIndex=0, IconAtlas='SOFT_KITTY_CIV_ATLAS',
AlphaIconAtlas='SOFT_KITTY_ALPHA_ATLAS', MapImage='Art/DawnOfMan/UnaCourtMap.dds',
DawnOfManImage='Art/SoftKitty/DawnOfMan.dds', DawnOfManQuote='TXT_KEY_SOFT_KITTY_DAWN', DawnOfManAudio=''
WHERE Type='CIVILIZATION_TRENT_SOFT_KITTY';

UPDATE Leaders SET Description='TXT_KEY_SOFT_KITTY_LEADER', Civilopedia='TXT_KEY_SOFT_KITTY_LEADER_PEDIA',
CivilopediaTag='TXT_KEY_CIV5_SOFT_KITTY_LEADER', ArtDefineTag='Art/SoftKitty/LeaderScene.xml',
PrimaryVictoryPursuit='VICTORY_PURSUIT_CULTURE', SecondaryVictoryPursuit='VICTORY_PURSUIT_DIPLOMACY',
VictoryCompetitiveness=7, WonderCompetitiveness=6, MinorCivCompetitiveness=8,
Boldness=3, DiploBalance=9, WarmongerHate=8, DoFWillingness=10, DenounceWillingness=3,
WorkWithWillingness=9, WorkAgainstWillingness=3, Loyalty=9, Forgiveness=9, Neediness=5,
Meanness=2, Chattiness=9, PortraitIndex=1, IconAtlas='SOFT_KITTY_ATLAS'
WHERE Type='LEADER_TRENT_SOFT_KITTY';
INSERT INTO Leader_Traits VALUES ('LEADER_TRENT_SOFT_KITTY','TRAIT_TRENT_SOFT_KITTY');
INSERT INTO Civilization_Leaders VALUES ('CIVILIZATION_TRENT_SOFT_KITTY','LEADER_TRENT_SOFT_KITTY');
INSERT INTO Leader_MajorCivApproachBiases (LeaderType,MajorCivApproachType,Bias)
SELECT 'LEADER_TRENT_SOFT_KITTY',MajorCivApproachType,
CASE MajorCivApproachType WHEN 'MAJOR_CIV_APPROACH_FRIENDLY' THEN 10 WHEN 'MAJOR_CIV_APPROACH_NEUTRAL' THEN 6
WHEN 'MAJOR_CIV_APPROACH_GUARDED' THEN 3 ELSE 1 END
FROM Leader_MajorCivApproachBiases WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Leader_MinorCivApproachBiases (LeaderType,MinorCivApproachType,Bias)
SELECT 'LEADER_TRENT_SOFT_KITTY',MinorCivApproachType,Bias FROM Leader_MinorCivApproachBiases WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Leader_Flavors (LeaderType,FlavorType,Flavor)
SELECT 'LEADER_TRENT_SOFT_KITTY',FlavorType,
CASE FlavorType WHEN 'FLAVOR_CULTURE' THEN 9 WHEN 'FLAVOR_GREAT_PEOPLE' THEN 8
WHEN 'FLAVOR_DIPLOMACY' THEN 9 WHEN 'FLAVOR_HAPPINESS' THEN 7 WHEN 'FLAVOR_TRADE_ROUTE' THEN 7
WHEN 'FLAVOR_GROWTH' THEN 6 WHEN 'FLAVOR_WONDER' THEN 6 WHEN 'FLAVOR_EXPANSION' THEN 4
WHEN 'FLAVOR_OFFENSE' THEN 3 WHEN 'FLAVOR_RELIGION' THEN 3 ELSE 5 END
FROM Leader_Flavors WHERE LeaderType='LEADER_WASHINGTON';
-- Copy every response category before replacing selected lines, avoiding missing greetings.
INSERT INTO Diplomacy_Responses (LeaderType,ResponseType,Response,Bias)
SELECT 'LEADER_TRENT_SOFT_KITTY',ResponseType,Response,Bias FROM Diplomacy_Responses WHERE LeaderType='LEADER_WASHINGTON';

INSERT INTO Civilization_FreeBuildingClasses VALUES ('CIVILIZATION_TRENT_SOFT_KITTY','BUILDINGCLASS_PALACE');
INSERT INTO Civilization_FreeTechs VALUES ('CIVILIZATION_TRENT_SOFT_KITTY','TECH_AGRICULTURE');
-- The difficulty/era starting-defense package provides the normal Warrior.
INSERT INTO Civilization_FreeUnits (CivilizationType,UnitClassType,UnitAIType,Count) VALUES
('CIVILIZATION_TRENT_SOFT_KITTY','UNITCLASS_SETTLER','UNITAI_SETTLE',1);

UPDATE Units SET Description='TXT_KEY_SOFT_KITTY_ROMANTIC',Civilopedia='TXT_KEY_SOFT_KITTY_ROMANTIC_PEDIA',
Strategy='TXT_KEY_SOFT_KITTY_ROMANTIC_STRATEGY',Help='TXT_KEY_SOFT_KITTY_ROMANTIC_HELP',
PortraitIndex=2,IconAtlas='SOFT_KITTY_ATLAS'
WHERE Type='UNIT_TRENT_HOPELESS_ROMANTIC';
INSERT INTO Civilization_UnitClassOverrides VALUES
('CIVILIZATION_TRENT_SOFT_KITTY','UNITCLASS_MUSICIAN','UNIT_TRENT_HOPELESS_ROMANTIC');

UPDATE Buildings SET Description='TXT_KEY_SOFT_KITTY_COMFORT',Civilopedia='TXT_KEY_SOFT_KITTY_COMFORT_PEDIA',
Strategy='TXT_KEY_SOFT_KITTY_COMFORT_STRATEGY',Help='TXT_KEY_SOFT_KITTY_COMFORT_HELP',
Happiness=Happiness+1, PortraitIndex=3,IconAtlas='SOFT_KITTY_ATLAS'
WHERE Type='BUILDING_TRENT_COMFORT_ROOM';
UPDATE Building_YieldChanges SET Yield=Yield+1
WHERE BuildingType='BUILDING_TRENT_COMFORT_ROOM' AND YieldType='YIELD_CULTURE';
INSERT INTO Building_YieldChanges (BuildingType,YieldType,Yield)
SELECT 'BUILDING_TRENT_COMFORT_ROOM','YIELD_CULTURE',1 WHERE NOT EXISTS
(SELECT 1 FROM Building_YieldChanges WHERE BuildingType='BUILDING_TRENT_COMFORT_ROOM' AND YieldType='YIELD_CULTURE');
UPDATE Building_SpecificGreatPersonRateModifier SET Modifier=Modifier+10
WHERE BuildingType='BUILDING_TRENT_COMFORT_ROOM' AND SpecialistType='SPECIALIST_MUSICIAN';
INSERT INTO Building_SpecificGreatPersonRateModifier (BuildingType,SpecialistType,Modifier)
SELECT 'BUILDING_TRENT_COMFORT_ROOM','SPECIALIST_MUSICIAN',10 WHERE NOT EXISTS
(SELECT 1 FROM Building_SpecificGreatPersonRateModifier WHERE BuildingType='BUILDING_TRENT_COMFORT_ROOM' AND SpecialistType='SPECIALIST_MUSICIAN');
INSERT INTO Civilization_BuildingClassOverrides VALUES
('CIVILIZATION_TRENT_SOFT_KITTY','BUILDINGCLASS_OPERA_HOUSE','BUILDING_TRENT_COMFORT_ROOM');

INSERT INTO UnitPromotions (Type,Description,Help,CannotBeChosen,LostWithUpgrade,CombatPercent,MovesChange,ShowInUnitPanel,IsVisibleAboveFlag,PortraitIndex,IconAtlas) VALUES
('PROMOTION_TRENT_REPERCUSSION_COMBAT','TXT_KEY_SOFT_KITTY_REPERCUSSIONS','TXT_KEY_SOFT_KITTY_COMBAT_HELP',1,0,-10,0,0,0,5,'SOFT_KITTY_ATLAS'),
('PROMOTION_TRENT_REPERCUSSION_MOVEMENT','TXT_KEY_SOFT_KITTY_REPERCUSSIONS','TXT_KEY_SOFT_KITTY_MOVEMENT_HELP',1,0,0,-1,0,0,5,'SOFT_KITTY_ATLAS');

CREATE TEMP TABLE SoftKittyPenalty (N INTEGER);
INSERT INTO SoftKittyPenalty VALUES (1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15);
INSERT INTO BuildingClasses (Type,DefaultBuilding,Description)
SELECT 'BUILDINGCLASS_TRENT_REPERCUSSION_PROD_'||N,'BUILDING_TRENT_REPERCUSSION_PROD_'||N,'TXT_KEY_SOFT_KITTY_REPERCUSSIONS' FROM SoftKittyPenalty;
INSERT INTO Buildings (Type,BuildingClass,Description,Cost,FaithCost,IsDummy,ShowInPedia,NeverCapture,NukeImmune,ConquestProb,PortraitIndex,IconAtlas)
SELECT 'BUILDING_TRENT_REPERCUSSION_PROD_'||N,'BUILDINGCLASS_TRENT_REPERCUSSION_PROD_'||N,'TXT_KEY_SOFT_KITTY_REPERCUSSIONS',-1,-1,1,0,1,1,0,5,'SOFT_KITTY_ATLAS' FROM SoftKittyPenalty;
INSERT INTO Building_YieldModifiers (BuildingType,YieldType,Yield)
SELECT 'BUILDING_TRENT_REPERCUSSION_PROD_'||N,'YIELD_PRODUCTION',-N FROM SoftKittyPenalty;
DROP TABLE SoftKittyPenalty;

INSERT INTO BuildingClasses (Type,DefaultBuilding,Description) VALUES
('BUILDINGCLASS_TRENT_REPERCUSSION_DUMMY','BUILDING_TRENT_REPERCUSSION_DUMMY','TXT_KEY_SOFT_KITTY_REPERCUSSIONS'),
('BUILDINGCLASS_TRENT_COMFORT_RECOVERY_DUMMY','BUILDING_TRENT_COMFORT_RECOVERY_DUMMY','TXT_KEY_SOFT_KITTY_COMFORT'),
('BUILDINGCLASS_TRENT_MUSIC_DUMMY','BUILDING_TRENT_MUSIC_DUMMY','TXT_KEY_SOFT_KITTY_COMFORT');
INSERT INTO Buildings (Type,BuildingClass,Description,Cost,FaithCost,IsDummy,ShowInPedia,NeverCapture,NukeImmune,ConquestProb,GreatPeopleRateModifier,PortraitIndex,IconAtlas) VALUES
('BUILDING_TRENT_REPERCUSSION_DUMMY','BUILDINGCLASS_TRENT_REPERCUSSION_DUMMY','TXT_KEY_SOFT_KITTY_REPERCUSSIONS',-1,-1,1,0,1,1,0,-20,5,'SOFT_KITTY_ATLAS'),
('BUILDING_TRENT_COMFORT_RECOVERY_DUMMY','BUILDINGCLASS_TRENT_COMFORT_RECOVERY_DUMMY','TXT_KEY_SOFT_KITTY_COMFORT',-1,-1,1,0,1,1,0,0,3,'SOFT_KITTY_ATLAS'),
('BUILDING_TRENT_MUSIC_DUMMY','BUILDINGCLASS_TRENT_MUSIC_DUMMY','TXT_KEY_SOFT_KITTY_COMFORT',-1,-1,1,0,1,1,0,0,3,'SOFT_KITTY_ATLAS');
INSERT INTO Building_YieldChanges (BuildingType,YieldType,Yield) VALUES
('BUILDING_TRENT_COMFORT_RECOVERY_DUMMY','YIELD_CULTURE',3),
('BUILDING_TRENT_MUSIC_DUMMY','YIELD_CULTURE',1);
