-- Trent, the Library Exile. Bonuses are applied by Lua through hidden buildings.
UPDATE CustomModOptions SET Value=1 WHERE Name='EVENTS_GREAT_PEOPLE';

INSERT INTO Colors (Type,Red,Green,Blue,Alpha) VALUES
('COLOR_TRENT_LIBRARY_NAVY',0.035,0.075,0.16,1),
('COLOR_TRENT_LIBRARY_GOLD',0.88,0.66,0.27,1);
INSERT INTO PlayerColors (Type,PrimaryColor,SecondaryColor,TextColor) VALUES
('PLAYERCOLOR_TRENT_LIBRARY_EXILE','COLOR_TRENT_LIBRARY_NAVY','COLOR_TRENT_LIBRARY_GOLD','COLOR_PLAYER_WHITE_TEXT');
INSERT INTO Traits (Type,Description,ShortDescription) VALUES
('TRAIT_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_TRAIT_HELP','TXT_KEY_LIBRARY_EXILE_TRAIT');

UPDATE Civilizations SET Description='TXT_KEY_LIBRARY_EXILE_CIV',ShortDescription='TXT_KEY_LIBRARY_EXILE_SHORT',
Adjective='TXT_KEY_LIBRARY_EXILE_ADJECTIVE',Civilopedia='TXT_KEY_LIBRARY_EXILE_PEDIA',
CivilopediaTag='TXT_KEY_CIV5_LIBRARY_EXILE',Strategy='TXT_KEY_LIBRARY_EXILE_STRATEGY',Playable=1,AIPlayable=1,
DefaultPlayerColor='PLAYERCOLOR_TRENT_LIBRARY_EXILE',PortraitIndex=0,IconAtlas='LIBRARY_EXILE_CIV_ATLAS_V2',
AlphaIconAtlas='LIBRARY_EXILE_ALPHA_ATLAS',MapImage='Art/LibraryExile/MapImage.dds',
DawnOfManImage='Art/LibraryExile/DawnOfMan.dds',DawnOfManQuote='TXT_KEY_LIBRARY_EXILE_DAWN',DawnOfManAudio=''
WHERE Type='CIVILIZATION_TRENT_LIBRARY_EXILE';

UPDATE Leaders SET Description='TXT_KEY_LIBRARY_EXILE_LEADER',Civilopedia='TXT_KEY_LIBRARY_EXILE_LEADER_PEDIA',
CivilopediaTag='TXT_KEY_CIV5_LIBRARY_EXILE_LEADER',ArtDefineTag='Art/LibraryExile/LeaderScene.xml',
PrimaryVictoryPursuit='VICTORY_PURSUIT_SCIENCE',SecondaryVictoryPursuit='VICTORY_PURSUIT_CULTURE',
VictoryCompetitiveness=6,WonderCompetitiveness=6,MinorCivCompetitiveness=5,
Boldness=3,DiploBalance=8,WarmongerHate=8,DoFWillingness=8,DenounceWillingness=3,
WorkWithWillingness=7,WorkAgainstWillingness=3,Loyalty=9,Forgiveness=5,Neediness=4,
Meanness=3,Chattiness=3,PortraitIndex=1,IconAtlas='LIBRARY_EXILE_LEADER_ATLAS_V2'
WHERE Type='LEADER_TRENT_LIBRARY_EXILE';
INSERT INTO Leader_Traits VALUES ('LEADER_TRENT_LIBRARY_EXILE','TRAIT_TRENT_LIBRARY_EXILE');
INSERT INTO Civilization_Leaders VALUES ('CIVILIZATION_TRENT_LIBRARY_EXILE','LEADER_TRENT_LIBRARY_EXILE');
INSERT INTO Leader_MajorCivApproachBiases (LeaderType,MajorCivApproachType,Bias)
SELECT 'LEADER_TRENT_LIBRARY_EXILE',MajorCivApproachType,
CASE MajorCivApproachType WHEN 'MAJOR_CIV_APPROACH_FRIENDLY' THEN 7 WHEN 'MAJOR_CIV_APPROACH_NEUTRAL' THEN 8
WHEN 'MAJOR_CIV_APPROACH_GUARDED' THEN 5 WHEN 'MAJOR_CIV_APPROACH_AFRAID' THEN 2 ELSE 1 END
FROM Leader_MajorCivApproachBiases WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Leader_MinorCivApproachBiases (LeaderType,MinorCivApproachType,Bias)
SELECT 'LEADER_TRENT_LIBRARY_EXILE',MinorCivApproachType,Bias FROM Leader_MinorCivApproachBiases WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Leader_Flavors (LeaderType,FlavorType,Flavor)
SELECT 'LEADER_TRENT_LIBRARY_EXILE',FlavorType,
CASE FlavorType WHEN 'FLAVOR_SCIENCE' THEN 8 WHEN 'FLAVOR_CULTURE' THEN 8 WHEN 'FLAVOR_GREAT_PEOPLE' THEN 8
WHEN 'FLAVOR_DEFENSE' THEN 7 WHEN 'FLAVOR_GROWTH' THEN 7 WHEN 'FLAVOR_WONDER' THEN 6
WHEN 'FLAVOR_DIPLOMACY' THEN 5 WHEN 'FLAVOR_EXPANSION' THEN 4 WHEN 'FLAVOR_OFFENSE' THEN 3
WHEN 'FLAVOR_NAVAL' THEN 3 ELSE 5 END
FROM Leader_Flavors WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Diplomacy_Responses (LeaderType,ResponseType,Response,Bias)
SELECT 'LEADER_TRENT_LIBRARY_EXILE',ResponseType,Response,Bias FROM Diplomacy_Responses WHERE LeaderType='LEADER_WASHINGTON';

INSERT INTO Civilization_FreeBuildingClasses VALUES ('CIVILIZATION_TRENT_LIBRARY_EXILE','BUILDINGCLASS_PALACE');
INSERT INTO Civilization_FreeTechs VALUES ('CIVILIZATION_TRENT_LIBRARY_EXILE','TECH_AGRICULTURE');
-- Difficulty and era setup supply the ordinary starting Warrior.
INSERT INTO Civilization_FreeUnits (CivilizationType,UnitClassType,UnitAIType,Count) VALUES
('CIVILIZATION_TRENT_LIBRARY_EXILE','UNITCLASS_SETTLER','UNITAI_SETTLE',1);

UPDATE Buildings SET Description='TXT_KEY_LIBRARY_EXILE_SCHOOL_LIBRARY',Civilopedia='TXT_KEY_LIBRARY_EXILE_SCHOOL_LIBRARY_PEDIA',
Strategy='TXT_KEY_LIBRARY_EXILE_SCHOOL_LIBRARY_STRATEGY',Help='TXT_KEY_LIBRARY_EXILE_SCHOOL_LIBRARY_HELP',
GoldMaintenance=1,SpecialistType='SPECIALIST_WRITER',GreatPeopleRateChange=COALESCE(GreatPeopleRateChange,0)+1,
GreatWorkSlotType='GREAT_WORK_SLOT_LITERATURE',GreatWorkCount=COALESCE(GreatWorkCount,0)+1,
PortraitIndex=3,IconAtlas='LIBRARY_EXILE_ATLAS'
WHERE Type='BUILDING_TRENT_SCHOOL_LIBRARY';
UPDATE Building_YieldChanges SET Yield=Yield+1
WHERE BuildingType='BUILDING_TRENT_SCHOOL_LIBRARY' AND YieldType='YIELD_CULTURE';
INSERT INTO Building_YieldChanges (BuildingType,YieldType,Yield)
SELECT 'BUILDING_TRENT_SCHOOL_LIBRARY','YIELD_CULTURE',1 WHERE NOT EXISTS
(SELECT 1 FROM Building_YieldChanges WHERE BuildingType='BUILDING_TRENT_SCHOOL_LIBRARY' AND YieldType='YIELD_CULTURE');
INSERT INTO Civilization_BuildingClassOverrides VALUES
('CIVILIZATION_TRENT_LIBRARY_EXILE','BUILDINGCLASS_LIBRARY','BUILDING_TRENT_SCHOOL_LIBRARY');

UPDATE Units SET Description='TXT_KEY_LIBRARY_EXILE_READER',Civilopedia='TXT_KEY_LIBRARY_EXILE_READER_PEDIA',
Strategy='TXT_KEY_LIBRARY_EXILE_READER_STRATEGY',Help='TXT_KEY_LIBRARY_EXILE_READER_HELP',
PortraitIndex=2,IconAtlas='LIBRARY_EXILE_ATLAS'
WHERE Type='UNIT_TRENT_IPAD_READER';
INSERT INTO Civilization_UnitClassOverrides VALUES
('CIVILIZATION_TRENT_LIBRARY_EXILE','UNITCLASS_WRITER','UNIT_TRENT_IPAD_READER');

INSERT INTO BuildingClasses (Type,DefaultBuilding,Description) VALUES
('BUILDINGCLASS_TRENT_EXILE_1','BUILDING_TRENT_EXILE_1','TXT_KEY_LIBRARY_EXILE_TRAIT'),
('BUILDINGCLASS_TRENT_EXILE_2','BUILDING_TRENT_EXILE_2','TXT_KEY_LIBRARY_EXILE_TRAIT'),
('BUILDINGCLASS_TRENT_EXILE_3','BUILDING_TRENT_EXILE_3','TXT_KEY_LIBRARY_EXILE_TRAIT'),
('BUILDINGCLASS_TRENT_VISITOR_WRITER','BUILDING_TRENT_VISITOR_WRITER','TXT_KEY_LIBRARY_EXILE_VISITOR'),
('BUILDINGCLASS_TRENT_VISITOR_HAPPINESS','BUILDING_TRENT_VISITOR_HAPPINESS','TXT_KEY_LIBRARY_EXILE_VISITOR'),
('BUILDINGCLASS_TRENT_VISITOR_CULTURE','BUILDING_TRENT_VISITOR_CULTURE','TXT_KEY_LIBRARY_EXILE_VISITOR'),
('BUILDINGCLASS_TRENT_READER_CITY','BUILDING_TRENT_READER_CITY','TXT_KEY_LIBRARY_EXILE_READER');
INSERT INTO Buildings (Type,BuildingClass,Description,Cost,FaithCost,IsDummy,ShowInPedia,NeverCapture,NukeImmune,ConquestProb,Happiness,PortraitIndex,IconAtlas) VALUES
('BUILDING_TRENT_EXILE_1','BUILDINGCLASS_TRENT_EXILE_1','TXT_KEY_LIBRARY_EXILE_TRAIT',-1,-1,1,0,1,1,0,0,0,'LIBRARY_EXILE_ATLAS'),
('BUILDING_TRENT_EXILE_2','BUILDINGCLASS_TRENT_EXILE_2','TXT_KEY_LIBRARY_EXILE_TRAIT',-1,-1,1,0,1,1,0,0,0,'LIBRARY_EXILE_ATLAS'),
('BUILDING_TRENT_EXILE_3','BUILDINGCLASS_TRENT_EXILE_3','TXT_KEY_LIBRARY_EXILE_TRAIT',-1,-1,1,0,1,1,0,0,0,'LIBRARY_EXILE_ATLAS'),
('BUILDING_TRENT_VISITOR_WRITER','BUILDINGCLASS_TRENT_VISITOR_WRITER','TXT_KEY_LIBRARY_EXILE_VISITOR',-1,-1,1,0,1,1,0,0,0,'LIBRARY_EXILE_ATLAS'),
('BUILDING_TRENT_VISITOR_HAPPINESS','BUILDINGCLASS_TRENT_VISITOR_HAPPINESS','TXT_KEY_LIBRARY_EXILE_VISITOR',-1,-1,1,0,1,1,0,2,0,'LIBRARY_EXILE_ATLAS'),
('BUILDING_TRENT_VISITOR_CULTURE','BUILDINGCLASS_TRENT_VISITOR_CULTURE','TXT_KEY_LIBRARY_EXILE_VISITOR',-1,-1,1,0,1,1,0,0,0,'LIBRARY_EXILE_ATLAS'),
('BUILDING_TRENT_READER_CITY','BUILDINGCLASS_TRENT_READER_CITY','TXT_KEY_LIBRARY_EXILE_READER',-1,-1,1,0,1,1,0,0,2,'LIBRARY_EXILE_ATLAS');
INSERT INTO Building_YieldModifiers (BuildingType,YieldType,Yield) VALUES
('BUILDING_TRENT_EXILE_1','YIELD_SCIENCE',3),('BUILDING_TRENT_EXILE_1','YIELD_CULTURE',3),
('BUILDING_TRENT_EXILE_2','YIELD_SCIENCE',6),('BUILDING_TRENT_EXILE_2','YIELD_CULTURE',6),
('BUILDING_TRENT_EXILE_3','YIELD_SCIENCE',9),('BUILDING_TRENT_EXILE_3','YIELD_CULTURE',9);
INSERT INTO Building_SpecificGreatPersonRateModifier (BuildingType,SpecialistType,Modifier) VALUES
('BUILDING_TRENT_VISITOR_WRITER','SPECIALIST_WRITER',15);
INSERT INTO Building_YieldChanges (BuildingType,YieldType,Yield) VALUES
('BUILDING_TRENT_VISITOR_CULTURE','YIELD_CULTURE',1),
('BUILDING_TRENT_READER_CITY','YIELD_SCIENCE',2),
('BUILDING_TRENT_READER_CITY','YIELD_CULTURE',2);
