INSERT OR REPLACE INTO Language_en_US (Tag,Text) VALUES
('TXT_KEY_LIBRARY_EXILE_CIV','Trent - The Library Exile'),
('TXT_KEY_LIBRARY_EXILE_SHORT','The Library Exile'),
('TXT_KEY_LIBRARY_EXILE_ADJECTIVE','Exiled'),
('TXT_KEY_LIBRARY_EXILE_LEADER','Trent'),
('TXT_KEY_LIBRARY_EXILE_TRAIT','Banished to the Library'),
('TXT_KEY_LIBRARY_EXILE_VISITOR','The Visitor'),
('TXT_KEY_LIBRARY_EXILE_TRAIT_HELP','Cities with a School Library gain +3% [ICON_RESEARCH] Science and [ICON_CULTURE] Culture for each civilization denouncing or at war with Trent (max 3). The first civilization to declare friendship becomes The Visitor; while that friendship is active, gain +15% Great Writer generation, +2 [ICON_HAPPINESS_1] Happiness, and +1 [ICON_CULTURE] Culture in School Library cities.'),
('TXT_KEY_LIBRARY_EXILE_PEDIA','Banished from the friend-group table, Trent made the school library his domain. Hostility sharpens the Exile''s focus, while a single enduring friendship keeps solitude from becoming abandonment.'),
('TXT_KEY_LIBRARY_EXILE_STRATEGY','Develop a compact empire around early School Libraries. Defend against hostile civilizations rather than chasing conquest, preserve the first Declaration of Friendship, and station iPad Readers in library cities until their Great Works or Treatises are needed.'),
('TXT_KEY_CIV5_LIBRARY_EXILE','The Library Exile'),
('TXT_KEY_CIV5_LIBRARY_EXILE_HEADING_1','Banished from the table'),
('TXT_KEY_CIV5_LIBRARY_EXILE_TEXT_1','Once there were five friends: Gabriel, Trent, Lachlan, Dion and Michael. After the Disagreement divided the group, Trent was not banished from school or civilization, but from the table. He retreated to the school library, where isolation became routine and stories filled the silence.'),
('TXT_KEY_CIV5_LIBRARY_EXILE_HEADING_2','Exile Stacks'),
('TXT_KEY_CIV5_LIBRARY_EXILE_TEXT_2','Every living major civilization currently denouncing Trent or at war with him supplies one Exile Stack, whether it meets one condition or both. A maximum of three stacks is counted. Each stack gives +3% Science and +3% Culture in every city containing a School Library, for a maximum of +9% to each yield. The modifier disappears immediately after reconciliation or peace is detected.[NEWLINE][NEWLINE]The bonus does not improve military power. Trent is rewarded for surviving diplomatic hostility, not for provoking wars he cannot defend.'),
('TXT_KEY_CIV5_LIBRARY_EXILE_HEADING_3','The Visitor'),
('TXT_KEY_CIV5_LIBRARY_EXILE_TEXT_3','The first civilization to share an active Declaration of Friendship with Trent is permanently recorded as The Visitor. This identity cannot be reassigned, even after friendship expires or the Visitor is eliminated. While their friendship is active, every city gains +15% Great Writer generation, the empire gains +2 Happiness, and each School Library produces +1 additional Culture.[NEWLINE][NEWLINE]The Visitor never subtracts Exile Stacks created by other civilizations. If the friendship expires, its bonuses wait dormant until Trent and the same Visitor renew it.'),
('TXT_KEY_CIV5_LIBRARY_EXILE_HEADING_4','School Library'),
('TXT_KEY_CIV5_LIBRARY_EXILE_TEXT_4','The School Library replaces and inherits the currently loaded Community Patch Library: the same technology, cost, maintenance, population-based Science and other baseline effects. It additionally produces +1 Culture and +1 Great Writer Point and contains one Great Work of Writing slot. Only cities with a School Library receive Exile modifiers and the Visitor''s extra Culture.'),
('TXT_KEY_CIV5_LIBRARY_EXILE_HEADING_5','iPad Reader'),
('TXT_KEY_CIV5_LIBRARY_EXILE_TEXT_5','The iPad Reader replaces and inherits the active Great Writer. It may create a Great Work or write a Political Treatise normally. If it begins the turn stationed in a School Library city, that city gains +2 Science and +2 Culture for the turn; additional Readers in the same city do not stack. Expending an iPad Reader through a Great Person action also grants 25 Science multiplied by the current Era number, from 25 in the Ancient Era to 200 in the Information Era.'),
('TXT_KEY_CIV5_LIBRARY_EXILE_HEADING_6','Strategy: outlast the disagreement'),
('TXT_KEY_CIV5_LIBRARY_EXILE_TEXT_6','Three to five developed cities suit Trent well. Establish School Libraries early, guard the Visitor relationship, and use defensive forces to prevent hostile civilizations from converting a productive exile into defeat. Readers can sit in cities for reliable yields before becoming Great Works or Treatises at a decisive moment.[NEWLINE][NEWLINE]Against the Library Exile, neutral relations are the cleanest counter. Reconciliation removes Exile bonuses, pillaging library infrastructure breaks the engine, and early pressure arrives before the intellectual economy matures.'),
('TXT_KEY_CIV5_LIBRARY_EXILE_FACTOID_HEADING','Library maxim'),
('TXT_KEY_CIV5_LIBRARY_EXILE_FACTOID_TEXT','You can have the table. I''ll have the library.'),
('TXT_KEY_LIBRARY_EXILE_LEADER_PEDIA','Trent, the Banished Reader, turns social isolation into intellectual focus. Reserved, dry and occasionally petty, he remembers the one friend who continued to cross the room.'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER_NAME','Trent'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER','Trent, the Banished Reader'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER_SUBTITLE','The Banished Reader'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER_LIVED','The Era of the Disagreement'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER_TITLES_1','Exile of the School Library'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER_HEADING_1','There were once five'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER_TEXT_1','Gabriel, Trent, Lachlan, Dion and Michael once shared a table. Then disagreement became sides and sides became distance. Trent found himself separated from the group, carrying his iPad and charger toward a quieter place.'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER_HEADING_2','Enthroned among books'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER_TEXT_2','The school library became refuge, routine and eventually a kingdom. Trent read through arguments, lunch bells and thousands of pages. While others negotiated possession of the table, he built an empire out of uninterrupted thought.'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER_HEADING_3','One bridge remained'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER_TEXT_3','Gabriel still visited. The gesture did not end the exile, but it proved that isolation need not be abandonment. The Visitor became a permanent office in Trent''s political memory: not a replaceable alliance, but one relationship that survived the disagreement.'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER_HEADING_4','A brighter tomorrow'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER_TEXT_4','Hostility now gives Trent focus rather than fury. He does not seek conquest. He builds libraries, cultivates writers and waits for the world to discover that the person it pushed aside has quietly surpassed it.'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER_FACT_1','The Visitor''s identity persists through saves and cannot be replaced by a later friend.'),
('TXT_KEY_CIV5_LIBRARY_EXILE_LEADER_FACT_2','A civilization at war with and denouncing Trent still grants only one Exile Stack.'),
('TXT_KEY_LIBRARY_EXILE_DAWN','There were once five friends: Gabriel, Trent, Lachlan, Dion and Michael.[NEWLINE][NEWLINE]Then came disagreement. Words became sides, sides became distance, and eventually Trent found himself separated from the table he once shared with the others.[NEWLINE][NEWLINE]He retreated to the school library. Amid bookshelves, charging cables and the glow of a tablet screen, exile became routine and countless stories filled the silence. Yet one friendship crossed the divide. Gabriel continued to visit.[NEWLINE][NEWLINE]And so the Library Exile learned that hostility could become focus, solitude could become strength, and one person crossing the room could be worth more than an entire table.[NEWLINE][NEWLINE]Trent, Banished Reader — will the library remain merely your refuge, or become the foundation of a civilization that stands the test of time?'),
('TXT_KEY_LIBRARY_EXILE_SCHOOL_LIBRARY','School Library'),
('TXT_KEY_LIBRARY_EXILE_SCHOOL_LIBRARY_HELP','Replaces the Library and retains its active Community Patch benefits. Adds +1 [ICON_CULTURE] Culture, +1 Great Writer Point, and one Great Work of Writing slot. Receives Banished to the Library modifiers and +1 [ICON_CULTURE] Culture while The Visitor friendship is active.'),
('TXT_KEY_LIBRARY_EXILE_SCHOOL_LIBRARY_STRATEGY','Build School Libraries throughout a developed empire. They are required for Exile yield modifiers, the iPad Reader''s stationed bonus, and the Visitor''s additional Culture.'),
('TXT_KEY_LIBRARY_EXILE_SCHOOL_LIBRARY_PEDIA','After the Disagreement, a quiet corner of the school library became Trent''s seat of power. A tablet, a charger and enough stories to outlast every argument proved to be all the infrastructure an exile required.[NEWLINE][NEWLINE]This unique building inherits every current Community Patch Library property before adding its Culture, Great Writer Point and writing slot.'),
('TXT_KEY_LIBRARY_EXILE_READER','iPad Reader'),
('TXT_KEY_LIBRARY_EXILE_READER_HELP','Replaces the Great Writer and retains Great Works and Political Treatises. When stationed in a School Library city at the start of the turn, provides +2 [ICON_RESEARCH] Science and +2 [ICON_CULTURE] Culture there; one per city. Expending it through a Great Person action grants 25 [ICON_RESEARCH] Science per Era number.'),
('TXT_KEY_LIBRARY_EXILE_READER_STRATEGY','Station an iPad Reader in a School Library for passive Science and Culture, then expend it when a Great Work or Political Treatise is worth more. Multiple Readers in one city do not stack.'),
('TXT_KEY_LIBRARY_EXILE_READER_PEDIA','The iPad Reader has weaponized the oldest response to group drama: finding a quiet chair and reading something extremely long. Its tablet glow marks a city as an active refuge.[NEWLINE][NEWLINE]The unit inherits the currently loaded Community Patch Great Writer, including its normal Great Work names and missions. Its Science reward applies only when a Great Person action expends the Reader, not when it is killed.'),
('TXT_KEY_LIBRARY_EXILE_VISITOR_TITLE','The Visitor'),
('TXT_KEY_LIBRARY_EXILE_VISITOR_BODY','{1_CivName} is the first civilization to cross the room. It is permanently designated The Visitor.'),
('TXT_KEY_LIBRARY_EXILE_STACK_TITLE','Exile changes'),
('TXT_KEY_LIBRARY_EXILE_STACK_BODY','Trent now has {1_Num} Exile Stack(s): School Library cities receive +{2_Percent}% Science and Culture.'),
('TXT_KEY_LIBRARY_EXILE_READER_TITLE','One more chapter'),
('TXT_KEY_LIBRARY_EXILE_READER_BODY','The expended iPad Reader adds {1_Num} Science to current research.'),
('TXT_KEY_LIBRARY_EXILE_INTRO','Oh. Hey. Trent. You can stay if you want. It''s quieter here anyway.'),
('TXT_KEY_LIBRARY_EXILE_NEUTRAL','Hey. I''m just reading something.'),
('TXT_KEY_LIBRARY_EXILE_FRIENDLY','Gabriel usually visits around this time. Pull up a chair.'),
('TXT_KEY_LIBRARY_EXILE_HOSTILE','Did Michael send you?'),
('TXT_KEY_LIBRARY_EXILE_DOF','Sure. Just don''t suddenly decide you''re taking someone else''s side.'),
('TXT_KEY_LIBRARY_EXILE_DOW','I was perfectly happy sitting there reading. You made this necessary.'),
('TXT_KEY_LIBRARY_EXILE_ATTACKED','So exile wasn''t enough?'),
('TXT_KEY_LIBRARY_EXILE_DEFEATED','Guess they finally closed the library.'),
('TXT_KEY_LIBRARY_EXILE_ACCEPT','Fine. That seems reasonable.'),
('TXT_KEY_LIBRARY_EXILE_REJECT','No. I have enough interruptions already.'),
('TXT_KEY_LIBRARY_EXILE_DENOUNCED','Cool. I''ll be in the library.'),
('TXT_KEY_LIBRARY_EXILE_RARE_HOSTILE','I''ve had disagreements before. They usually end with me relocating.'),
('TXT_KEY_LIBRARY_EXILE_CITY_1','The School Library'),
('TXT_KEY_LIBRARY_EXILE_CITY_2','The Back Table'),
('TXT_KEY_LIBRARY_EXILE_CITY_3','Quiet Study Area'),
('TXT_KEY_LIBRARY_EXILE_CITY_4','The Charging Port'),
('TXT_KEY_LIBRARY_EXILE_CITY_5','Behind the Bookshelves'),
('TXT_KEY_LIBRARY_EXILE_CITY_6','The Empty Seat'),
('TXT_KEY_LIBRARY_EXILE_CITY_7','Fanfiction Archive'),
('TXT_KEY_LIBRARY_EXILE_CITY_8','The iPad Corner'),
('TXT_KEY_LIBRARY_EXILE_CITY_9','Lunchtime Refuge'),
('TXT_KEY_LIBRARY_EXILE_CITY_10','Restricted Section'),
('TXT_KEY_LIBRARY_EXILE_CITY_11','The Reading Room'),
('TXT_KEY_LIBRARY_EXILE_CITY_12','Last Available Charger'),
('TXT_KEY_LIBRARY_EXILE_CITY_13','Silent Study'),
('TXT_KEY_LIBRARY_EXILE_CITY_14','The Computer Lab'),
('TXT_KEY_LIBRARY_EXILE_CITY_15','The Forgotten Table'),
('TXT_KEY_LIBRARY_EXILE_CITY_16','After-School Library'),
('TXT_KEY_LIBRARY_EXILE_CITY_17','The Long Chapter'),
('TXT_KEY_LIBRARY_EXILE_CITY_18','Incognito Tab'),
('TXT_KEY_LIBRARY_EXILE_CITY_19','Archive of Our Own'),
('TXT_KEY_LIBRARY_EXILE_CITY_20','The Final Bell');

INSERT INTO Civilization_CityNames (CivilizationType,CityName) VALUES
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_1'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_2'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_3'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_4'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_5'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_6'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_7'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_8'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_9'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_10'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_11'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_12'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_13'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_14'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_15'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_16'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_17'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_18'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_19'),
('CIVILIZATION_TRENT_LIBRARY_EXILE','TXT_KEY_LIBRARY_EXILE_CITY_20');
INSERT INTO Civilization_SpyNames (CivilizationType,SpyName)
SELECT 'CIVILIZATION_TRENT_LIBRARY_EXILE',SpyName FROM Civilization_SpyNames WHERE CivilizationType='CIVILIZATION_AMERICA';

UPDATE Diplomacy_Responses SET Response='TXT_KEY_LIBRARY_EXILE_INTRO',Bias=1 WHERE LeaderType='LEADER_TRENT_LIBRARY_EXILE' AND ResponseType='RESPONSE_FIRST_GREETING';
UPDATE Diplomacy_Responses SET Response='TXT_KEY_LIBRARY_EXILE_NEUTRAL',Bias=1 WHERE LeaderType='LEADER_TRENT_LIBRARY_EXILE' AND ResponseType='RESPONSE_GREETING_NEUTRAL_HELLO';
UPDATE Diplomacy_Responses SET Response='TXT_KEY_LIBRARY_EXILE_FRIENDLY',Bias=1 WHERE LeaderType='LEADER_TRENT_LIBRARY_EXILE' AND ResponseType='RESPONSE_GREETING_POLITE_HELLO';
UPDATE Diplomacy_Responses SET Response='TXT_KEY_LIBRARY_EXILE_HOSTILE',Bias=4 WHERE LeaderType='LEADER_TRENT_LIBRARY_EXILE' AND ResponseType='RESPONSE_GREETING_HOSTILE_HELLO';
INSERT INTO Diplomacy_Responses (LeaderType,ResponseType,Response,Bias) VALUES
('LEADER_TRENT_LIBRARY_EXILE','RESPONSE_GREETING_HOSTILE_HELLO','TXT_KEY_LIBRARY_EXILE_RARE_HOSTILE',1),
('LEADER_TRENT_LIBRARY_EXILE','RESPONSE_WORK_WITH_US_YES','TXT_KEY_LIBRARY_EXILE_DOF',1),
('LEADER_TRENT_LIBRARY_EXILE','RESPONSE_RESPONSE_TO_BEING_DENOUNCED','TXT_KEY_LIBRARY_EXILE_DENOUNCED',1);
UPDATE Diplomacy_Responses SET Response='TXT_KEY_LIBRARY_EXILE_DOW',Bias=1 WHERE LeaderType='LEADER_TRENT_LIBRARY_EXILE' AND ResponseType='RESPONSE_DOW_GENERIC';
UPDATE Diplomacy_Responses SET Response='TXT_KEY_LIBRARY_EXILE_ATTACKED',Bias=1 WHERE LeaderType='LEADER_TRENT_LIBRARY_EXILE' AND ResponseType='RESPONSE_ATTACKED_HOSTILE';
UPDATE Diplomacy_Responses SET Response='TXT_KEY_LIBRARY_EXILE_DEFEATED',Bias=1 WHERE LeaderType='LEADER_TRENT_LIBRARY_EXILE' AND ResponseType='RESPONSE_DEFEATED';
UPDATE Diplomacy_Responses SET Response='TXT_KEY_LIBRARY_EXILE_ACCEPT',Bias=1 WHERE LeaderType='LEADER_TRENT_LIBRARY_EXILE' AND ResponseType IN ('RESPONSE_TRADE_ACCEPT_ACCEPTABLE','RESPONSE_TRADE_ACCEPT_GENEROUS');
UPDATE Diplomacy_Responses SET Response='TXT_KEY_LIBRARY_EXILE_REJECT',Bias=1 WHERE LeaderType='LEADER_TRENT_LIBRARY_EXILE' AND ResponseType IN ('RESPONSE_TRADE_REJECT_INSULTING','RESPONSE_TRADE_REJECT_UNACCEPTABLE');
