-- Generated by Tools/build_phone_stealer_inheritance.py.
-- Copies the active CP Worker baseline at activation; values are not hardcoded.
CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Units" WHERE Type='UNIT_WORKER';
UPDATE PhoneStealerClone SET Type='UNIT_TRENT_UNA_COURT_BUTLER', ID=NULL;
INSERT INTO "Units" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Civilizations" WHERE Type='CIVILIZATION_AMERICA';
UPDATE PhoneStealerClone SET Type='CIVILIZATION_TRENT_PHONE_STEALER', ID=NULL;
INSERT INTO "Civilizations" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Leaders" WHERE Type='LEADER_WASHINGTON';
UPDATE PhoneStealerClone SET Type='LEADER_TRENT_PHONE_STEALER', ID=NULL;
INSERT INTO "Leaders" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "UnitGameplay2DScripts" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "UnitGameplay2DScripts" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_AITypes" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_AITypes" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_Bounties" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_Bounties" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_BuildOnFound" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_BuildOnFound" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_BuildingClassPurchaseRequireds" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_BuildingClassPurchaseRequireds" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_BuildingClassRequireds" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_BuildingClassRequireds" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_Buildings" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_Buildings" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_Builds" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_Builds" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_ClassUpgrades" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_ClassUpgrades" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_EraCombatStrength" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_EraCombatStrength" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_EraCombatType" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_EraCombatType" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_EraUnitPromotions" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_EraUnitPromotions" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_Flavors" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_Flavors" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_FreePromotions" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_FreePromotions" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_GreatPersons" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_GreatPersons" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_NotAITypes" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_NotAITypes" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_ProductionModifierBuildings" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_ProductionModifierBuildings" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_ProductionTraits" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_ProductionTraits" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_ResourceQuantityExpended" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_ResourceQuantityExpended" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_ResourceQuantityRequirements" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_ResourceQuantityRequirements" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_ResourceQuantityTotals" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_ResourceQuantityTotals" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_ScalingFromOwnedImprovements" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_ScalingFromOwnedImprovements" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_TechTypes" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_TechTypes" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_UniqueNames" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_UniqueNames" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_YieldFromBarbarianKills" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_YieldFromBarbarianKills" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_YieldFromKills" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_YieldFromKills" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;

CREATE TEMP TABLE PhoneStealerClone AS SELECT * FROM "Unit_YieldOnCompletion" WHERE UnitType='UNIT_WORKER';
UPDATE PhoneStealerClone SET UnitType='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO "Unit_YieldOnCompletion" SELECT * FROM PhoneStealerClone;
DROP TABLE PhoneStealerClone;
