-- Trent, the Phone Stealer. Phone missions, stash state and Butler escapes are Lua-driven.
UPDATE CustomModOptions SET Value=1 WHERE Name IN
('EVENTS_DIPLO_MODIFIERS','EVENTS_PLAYER_TURN','EVENTS_UNIT_CAPTURE','EVENTS_UNIT_PREKILL');

INSERT INTO Colors (Type,Red,Green,Blue,Alpha) VALUES
('COLOR_TRENT_PHONE_CRIMSON',0.43,0.035,0.035,1),
('COLOR_TRENT_PHONE_GOLD',0.94,0.72,0.31,1);
INSERT INTO PlayerColors (Type,PrimaryColor,SecondaryColor,TextColor) VALUES
('PLAYERCOLOR_TRENT_PHONE_STEALER','COLOR_TRENT_PHONE_CRIMSON','COLOR_TRENT_PHONE_GOLD','COLOR_PLAYER_WHITE_TEXT');
INSERT INTO Traits (Type,Description,ShortDescription) VALUES
('TRAIT_TRENT_PHONE_STEALER','TXT_KEY_PHONE_STEALER_TRAIT_HELP','TXT_KEY_PHONE_STEALER_TRAIT');

UPDATE Civilizations SET
Description='TXT_KEY_PHONE_STEALER_CIV',ShortDescription='TXT_KEY_PHONE_STEALER_SHORT',
Adjective='TXT_KEY_PHONE_STEALER_ADJECTIVE',Civilopedia='TXT_KEY_PHONE_STEALER_PEDIA',
CivilopediaTag='TXT_KEY_CIV5_PHONE_STEALER',Strategy='TXT_KEY_PHONE_STEALER_STRATEGY',
Playable=1,AIPlayable=1,DefaultPlayerColor='PLAYERCOLOR_TRENT_PHONE_STEALER',
PortraitIndex=0,IconAtlas='PHONE_STEALER_CIV_ATLAS',AlphaIconAtlas='PHONE_STEALER_ALPHA_ATLAS',
MapImage='Art/PhoneStealer/MapImage.dds',DawnOfManImage='Art/PhoneStealer/DawnOfMan.dds',
DawnOfManQuote='TXT_KEY_PHONE_STEALER_DAWN',DawnOfManAudio=''
WHERE Type='CIVILIZATION_TRENT_PHONE_STEALER';

UPDATE Leaders SET
Description='TXT_KEY_PHONE_STEALER_LEADER',Civilopedia='TXT_KEY_PHONE_STEALER_LEADER_PEDIA',
CivilopediaTag='TXT_KEY_CIV5_PHONE_STEALER_LEADER',ArtDefineTag='Art/PhoneStealer/LeaderScene.xml',
PrimaryVictoryPursuit='VICTORY_PURSUIT_SCIENCE',SecondaryVictoryPursuit='VICTORY_PURSUIT_DIPLOMACY',
VictoryCompetitiveness=7,WonderCompetitiveness=5,MinorCivCompetitiveness=5,
Boldness=7,DiploBalance=3,WarmongerHate=5,DoFWillingness=4,DenounceWillingness=7,
WorkWithWillingness=4,WorkAgainstWillingness=7,Loyalty=4,Forgiveness=2,Neediness=5,
Meanness=7,Chattiness=5,PortraitIndex=0,IconAtlas='PHONE_STEALER_LEADER_ATLAS'
WHERE Type='LEADER_TRENT_PHONE_STEALER';
INSERT INTO Leader_Traits VALUES ('LEADER_TRENT_PHONE_STEALER','TRAIT_TRENT_PHONE_STEALER');
INSERT INTO Civilization_Leaders VALUES ('CIVILIZATION_TRENT_PHONE_STEALER','LEADER_TRENT_PHONE_STEALER');

INSERT INTO Leader_MajorCivApproachBiases (LeaderType,MajorCivApproachType,Bias)
SELECT 'LEADER_TRENT_PHONE_STEALER',MajorCivApproachType,
CASE MajorCivApproachType
WHEN 'MAJOR_CIV_APPROACH_WAR' THEN 4 WHEN 'MAJOR_CIV_APPROACH_HOSTILE' THEN 6
WHEN 'MAJOR_CIV_APPROACH_DECEPTIVE' THEN 8 WHEN 'MAJOR_CIV_APPROACH_GUARDED' THEN 7
WHEN 'MAJOR_CIV_APPROACH_AFRAID' THEN 2 WHEN 'MAJOR_CIV_APPROACH_FRIENDLY' THEN 4
WHEN 'MAJOR_CIV_APPROACH_NEUTRAL' THEN 7 ELSE 5 END
FROM Leader_MajorCivApproachBiases WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Leader_MinorCivApproachBiases (LeaderType,MinorCivApproachType,Bias)
SELECT 'LEADER_TRENT_PHONE_STEALER',MinorCivApproachType,
CASE MinorCivApproachType WHEN 'MINOR_CIV_APPROACH_FRIENDLY' THEN 5
WHEN 'MINOR_CIV_APPROACH_PROTECTIVE' THEN 5 ELSE Bias END
FROM Leader_MinorCivApproachBiases WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Leader_Flavors (LeaderType,FlavorType,Flavor)
SELECT 'LEADER_TRENT_PHONE_STEALER',FlavorType,
CASE FlavorType
WHEN 'FLAVOR_ESPIONAGE' THEN 10 WHEN 'FLAVOR_SCIENCE' THEN 8 WHEN 'FLAVOR_GOLD' THEN 8
WHEN 'FLAVOR_CULTURE' THEN 5 WHEN 'FLAVOR_EXPANSION' THEN 5 WHEN 'FLAVOR_OFFENSE' THEN 5
WHEN 'FLAVOR_DEFENSE' THEN 6 WHEN 'FLAVOR_DIPLOMACY' THEN 4 WHEN 'FLAVOR_WONDER' THEN 5
WHEN 'FLAVOR_CITY_DEFENSE' THEN 6 ELSE 5 END
FROM Leader_Flavors WHERE LeaderType='LEADER_WASHINGTON';
INSERT INTO Diplomacy_Responses (LeaderType,ResponseType,Response,Bias)
SELECT 'LEADER_TRENT_PHONE_STEALER',ResponseType,Response,Bias
FROM Diplomacy_Responses WHERE LeaderType='LEADER_WASHINGTON';

INSERT INTO Civilization_FreeBuildingClasses VALUES
('CIVILIZATION_TRENT_PHONE_STEALER','BUILDINGCLASS_PALACE');
INSERT INTO Civilization_FreeTechs VALUES
('CIVILIZATION_TRENT_PHONE_STEALER','TECH_AGRICULTURE');
-- Difficulty and era setup supply the ordinary starting Warrior.
INSERT INTO Civilization_FreeUnits (CivilizationType,UnitClassType,UnitAIType,Count) VALUES
('CIVILIZATION_TRENT_PHONE_STEALER','UNITCLASS_SETTLER','UNITAI_SETTLE',1);

UPDATE Units SET
Description='TXT_KEY_PHONE_STEALER_BUTLER',Civilopedia='TXT_KEY_PHONE_STEALER_BUTLER_PEDIA',
Strategy='TXT_KEY_PHONE_STEALER_BUTLER_STRATEGY',Help='TXT_KEY_PHONE_STEALER_BUTLER_HELP',
Cost=CAST((Cost*120+99)/100 AS INTEGER),PortraitIndex=0,IconAtlas='PHONE_STEALER_BUTLER_ATLAS'
WHERE Type='UNIT_TRENT_UNA_COURT_BUTLER';
INSERT INTO UnitPromotions
(Type,Description,Help,CannotBeChosen,LostWithUpgrade,CannotBeCaptured,WorkRateMod,
 PortraitIndex,IconAtlas,PediaType,PediaEntry,Sound,ShowInUnitPanel,IsVisibleAboveFlag)
VALUES
('PROMOTION_TRENT_LOYALTY_TO_UNA_COURT','TXT_KEY_PROMOTION_TRENT_LOYALTY',
 'TXT_KEY_PROMOTION_TRENT_LOYALTY_HELP',1,0,1,25,0,'PHONE_STEALER_BUTLER_ATLAS',
 'PEDIA_ATTRIBUTES','TXT_KEY_PROMOTION_TRENT_LOYALTY','AS2D_IF_LEVELUP',1,1);
INSERT INTO Unit_FreePromotions (UnitType,PromotionType) VALUES
('UNIT_TRENT_UNA_COURT_BUTLER','PROMOTION_TRENT_LOYALTY_TO_UNA_COURT');
INSERT INTO Civilization_UnitClassOverrides VALUES
('CIVILIZATION_TRENT_PHONE_STEALER','UNITCLASS_WORKER','UNIT_TRENT_UNA_COURT_BUTLER');

-- Reuse the established Centrelink definition and art without modifying either.
INSERT INTO Civilization_BuildingClassOverrides VALUES
('CIVILIZATION_TRENT_PHONE_STEALER','BUILDINGCLASS_BANK','BUILDING_UNA_CENTRELINK');

-- Exactly one hidden capital building represents the complete Phone Stash.
CREATE TEMP TABLE PhoneStashCounts (N INTEGER);
INSERT INTO PhoneStashCounts VALUES
(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16),(17),(18),(19),(20),(21);
INSERT INTO BuildingClasses (Type,DefaultBuilding,Description)
SELECT 'BUILDINGCLASS_TRENT_PHONE_STASH_'||N,'BUILDING_TRENT_PHONE_STASH_'||N,
'TXT_KEY_PHONE_STEALER_STASH' FROM PhoneStashCounts;
INSERT INTO Buildings
(Type,BuildingClass,Description,Help,Cost,FaithCost,IsDummy,ShowInPedia,NeverCapture,NukeImmune,
 ConquestProb,Happiness,PortraitIndex,IconAtlas)
SELECT 'BUILDING_TRENT_PHONE_STASH_'||N,'BUILDINGCLASS_TRENT_PHONE_STASH_'||N,
'TXT_KEY_PHONE_STEALER_STASH','TXT_KEY_PHONE_STEALER_STASH_HELP',-1,-1,1,0,1,1,0,
CAST(N/3 AS INTEGER),0,'PHONE_STEALER_ABILITY_ATLAS' FROM PhoneStashCounts;
INSERT INTO Building_YieldChanges (BuildingType,YieldType,Yield)
SELECT 'BUILDING_TRENT_PHONE_STASH_'||N,'YIELD_SCIENCE',N*2 FROM PhoneStashCounts
UNION ALL SELECT 'BUILDING_TRENT_PHONE_STASH_'||N,'YIELD_GOLD',N*2 FROM PhoneStashCounts
UNION ALL SELECT 'BUILDING_TRENT_PHONE_STASH_'||N,'YIELD_CULTURE',N FROM PhoneStashCounts;
DROP TABLE PhoneStashCounts;

INSERT INTO DiploModifiers (Type,Description,ToCivilizationType) VALUES
('DIPLOMODIFIER_TRENT_STOLE_PHONE','TXT_KEY_PHONE_STEALER_DIPLO_MODIFIER',
 'CIVILIZATION_TRENT_PHONE_STEALER');
