INSERT INTO Language_en_US (Tag,Text) VALUES
('TXT_KEY_PHONE_STEALER_CIV','Princedom of Una Court'),
('TXT_KEY_PHONE_STEALER_SHORT','Una Court'),
('TXT_KEY_PHONE_STEALER_ADJECTIVE','Una Court'),
('TXT_KEY_PHONE_STEALER_LEADER','Trent — The Phone Stealer'),
('TXT_KEY_PHONE_STEALER_TRAIT','The Red-Headed Phone Snatcher'),
('TXT_KEY_PHONE_STEALER_TRAIT_HELP','Spies established in another major civilization''s Capital may begin Snatch Phone. After 8 turns on Standard Speed, that civilization''s unique Phone enters the Phone Stash. Each Phone grants the Capital +2 [ICON_RESEARCH] Science, +2 [ICON_GOLD] Gold and +1 [ICON_CULTURE] Culture; every 3 Phones grant +1 [ICON_HAPPINESS_1] Happiness. The victim receives a strong opinion penalty while Trent keeps the Phone. Phones may be returned; a returned Phone cannot be stolen again for 30 turns on Standard Speed.'),
('TXT_KEY_PHONE_STEALER_STRATEGY','Build a strong Capital, then place Spies in foreign Capitals and use the Phone Stash panel to begin eight-turn Snatch Phone missions. Each Phone permanently strengthens the Capital until returned, but its owner strongly resents Trent. Prefer distant enemies and weak rivals; return a Phone when repairing a crucial relationship is worth more than its yields.'),
('TXT_KEY_PHONE_STEALER_PEDIA','The Princedom of Una Court is a peculiar realm whose influence extends far beyond its modest borders. Under Trent, information, property and personal electronics have developed a surprisingly flexible definition of ownership. Every acquired device becomes another source of knowledge and opportunity, while its former owner demands an explanation.'),
('TXT_KEY_CIV5_PHONE_STEALER','The Princedom of Una Court'),
('TXT_KEY_CIV5_PHONE_STEALER_LEADER','Trent, the Phone Stealer'),
('TXT_KEY_PHONE_STEALER_DAWN','A brighter tomorrow — one Phone at a time.'),
('TXT_KEY_PHONE_STEALER_BUTLER','Una Court Butler'),
('TXT_KEY_PHONE_STEALER_BUTLER_HELP','Replaces the Worker. Costs 20% more [ICON_PRODUCTION] Production and works 25% faster. Loyalty to Una Court prevents permanent capture: when an enemy or Barbarian captures this unit, it escapes and reappears at Trent''s Capital or the nearest valid tile.'),
('TXT_KEY_PHONE_STEALER_BUTLER_STRATEGY','The Una Court Butler accelerates early improvements but is more expensive than an ordinary Worker. Its Loyalty makes dangerous border work less punishing, because a captured Butler escapes home instead of serving the captor.'),
('TXT_KEY_PHONE_STEALER_BUTLER_PEDIA','The household staff of Una Court are renowned for speed, discretion and an absolute refusal to remain in anybody else''s service. A Butler taken on campaign has an uncanny talent for reappearing at the palace before the captor has finished the paperwork.'),
('TXT_KEY_PROMOTION_TRENT_LOYALTY','Loyalty to Una Court'),
('TXT_KEY_PROMOTION_TRENT_LOYALTY_HELP','+25% Work Rate. Cannot be permanently captured; returns to Trent''s Capital after a capture attempt.'),
('TXT_KEY_PHONE_STEALER_STASH','Phone Stash'),
('TXT_KEY_PHONE_STEALER_STASH_HELP','Each stolen Phone grants this Capital +2 [ICON_RESEARCH] Science, +2 [ICON_GOLD] Gold and +1 [ICON_CULTURE] Culture. Every 3 Phones grant +1 [ICON_HAPPINESS_1] Happiness.'),
('TXT_KEY_PHONE_STEALER_DIPLO_MODIFIER','He Stole My Phone!'),
('TXT_KEY_PHONE_STEALER_NOTIFICATION_TITLE','Phone Snatched'),
('TXT_KEY_PHONE_STEALER_NOTIFICATION_BODY','%s completed the mission in %s and stole %s''s Phone.'),
('TXT_KEY_PHONE_STEALER_VICTIM_TITLE','He Stole My Phone!'),
('TXT_KEY_PHONE_STEALER_VICTIM_BODY','Trent''s agent stole your civilization''s Phone. The diplomatic grievance remains until he returns it.'),
('TXT_KEY_PHONE_STEALER_RETURN_TITLE','Phone Returned'),
('TXT_KEY_PHONE_STEALER_RETURN_BODY','Trent returned %s''s Phone. It cannot be stolen again for %s turns.'),
('TXT_KEY_PHONE_STEALER_ESCAPE_TITLE','A Loyal Butler Returns'),
('TXT_KEY_PHONE_STEALER_ESCAPE_BODY','The captured Una Court Butler escaped and returned to the Capital.'),
('TXT_KEY_CIV5_PHONE_STEALER_HEADING_1','A Small Court'),
('TXT_KEY_CIV5_PHONE_STEALER_TEXT_1','The Princedom of Una Court is modest in land but expansive in ambition. Its court treats information, opportunity and unattended electronics as resources waiting to be put to better use.'),
('TXT_KEY_CIV5_PHONE_STEALER_HEADING_2','The Phone Stash'),
('TXT_KEY_CIV5_PHONE_STEALER_TEXT_2','Trent''s agents catalogue one unique Phone for every major civilization. A stolen device remains useful even if its original civilization is later eliminated, unless Trent voluntarily returns it.'),
('TXT_KEY_CIV5_PHONE_STEALER_HEADING_3','Snatch Phone'),
('TXT_KEY_CIV5_PHONE_STEALER_TEXT_3','An established Spy in a foreign Capital can begin an eight-turn mission on Standard Speed. Moving the Spy away interrupts the attempt. A returned Phone is protected for thirty Standard-Speed turns.'),
('TXT_KEY_CIV5_PHONE_STEALER_HEADING_4','Accumulated Knowledge'),
('TXT_KEY_CIV5_PHONE_STEALER_TEXT_4','Every Phone contributes Science, Gold and Culture to the Capital. Larger collections also provide Happiness, rewarding a tall and economically developed heartland.'),
('TXT_KEY_CIV5_PHONE_STEALER_HEADING_5','Everybody Remembers'),
('TXT_KEY_CIV5_PHONE_STEALER_TEXT_5','The owner of every stolen Phone receives a strong personal grievance against Trent for as long as he keeps it. Collecting the world''s Phones can therefore create exceptional power and exceptional diplomatic isolation.'),
('TXT_KEY_CIV5_PHONE_STEALER_HEADING_6','People, Phones, Progress'),
('TXT_KEY_CIV5_PHONE_STEALER_TEXT_6','Una Court''s loyal Butlers build improvements quickly and escape capture, giving Trent the infrastructure needed to support his later espionage campaign.'),
('TXT_KEY_CIV5_PHONE_STEALER_LEADER_HEADING_1','The Red-Headed Ruler'),
('TXT_KEY_CIV5_PHONE_STEALER_LEADER_TEXT_1','Trent is remembered throughout Una Court for many things, but few habits generate as immediate a reaction as his tendency to acquire somebody else''s Phone.'),
('TXT_KEY_CIV5_PHONE_STEALER_LEADER_HEADING_2','An Instrument of Statecraft'),
('TXT_KEY_CIV5_PHONE_STEALER_LEADER_TEXT_2','As ruler, Trent elevates that habit into policy and dispatches agents across the world to collect the personal devices of foreign leaders.'),
('TXT_KEY_CIV5_PHONE_STEALER_LEADER_HEADING_3','Opportunity and Grievance'),
('TXT_KEY_CIV5_PHONE_STEALER_LEADER_TEXT_3','The more Phones Una Court collects, the more prosperous the Princedom becomes. Unfortunately, their owners remember exactly who took them.'),
('TXT_KEY_CIV5_PHONE_STEALER_LEADER_HEADING_4','Yours Today'),
('TXT_KEY_CIV5_PHONE_STEALER_LEADER_TEXT_4','Trent''s court motto is simple: yours today, his tomorrow.'),
('TXT_KEY_PHONE_STEALER_LEADER_PEDIA','Trent is remembered throughout Una Court for many things, but few habits have generated as immediate a reaction as his tendency to suddenly acquire somebody else''s Phone. As ruler he turns that habit into an instrument of statecraft.'),
('TXT_KEY_CIVILOPEDIA_LEADERS_PHONE_STEALER_NAME','Trent'),
('TXT_KEY_CIVILOPEDIA_LEADERS_PHONE_STEALER_SUBTITLE','The Phone Stealer'),
('TXT_KEY_CIVILOPEDIA_LEADERS_PHONE_STEALER_LIVED','The present day'),
('TXT_KEY_CIVILOPEDIA_LEADERS_PHONE_STEALER_TITLES_1','Prince of Una Court');

INSERT INTO Civilization_CityNames (CivilizationType,CityName) VALUES
('CIVILIZATION_TRENT_PHONE_STEALER','Una Court'),
('CIVILIZATION_TRENT_PHONE_STEALER','Phone Stash'),
('CIVILIZATION_TRENT_PHONE_STEALER','Small Court'),
('CIVILIZATION_TRENT_PHONE_STEALER','Big Plans'),
('CIVILIZATION_TRENT_PHONE_STEALER','Red Keep'),
('CIVILIZATION_TRENT_PHONE_STEALER','Butler''s Rest'),
('CIVILIZATION_TRENT_PHONE_STEALER','Golden Tray'),
('CIVILIZATION_TRENT_PHONE_STEALER','Tomorrow''s Court'),
('CIVILIZATION_TRENT_PHONE_STEALER','Ginger Crown'),
('CIVILIZATION_TRENT_PHONE_STEALER','Laurel Gate'),
('CIVILIZATION_TRENT_PHONE_STEALER','Progress Point'),
('CIVILIZATION_TRENT_PHONE_STEALER','Snatcher''s Reach'),
('CIVILIZATION_TRENT_PHONE_STEALER','Crimson Terrace'),
('CIVILIZATION_TRENT_PHONE_STEALER','Black Screen'),
('CIVILIZATION_TRENT_PHONE_STEALER','New Contact'),
('CIVILIZATION_TRENT_PHONE_STEALER','Airplane Mode'),
('CIVILIZATION_TRENT_PHONE_STEALER','Low Battery'),
('CIVILIZATION_TRENT_PHONE_STEALER','No Signal'),
('CIVILIZATION_TRENT_PHONE_STEALER','Unlocked'),
('CIVILIZATION_TRENT_PHONE_STEALER','More Phones');

INSERT INTO Civilization_SpyNames (CivilizationType,SpyName) VALUES
('CIVILIZATION_TRENT_PHONE_STEALER','TXT_KEY_SPY_NAME_PHONE_STEALER_0'),
('CIVILIZATION_TRENT_PHONE_STEALER','TXT_KEY_SPY_NAME_PHONE_STEALER_1'),
('CIVILIZATION_TRENT_PHONE_STEALER','TXT_KEY_SPY_NAME_PHONE_STEALER_2'),
('CIVILIZATION_TRENT_PHONE_STEALER','TXT_KEY_SPY_NAME_PHONE_STEALER_3'),
('CIVILIZATION_TRENT_PHONE_STEALER','TXT_KEY_SPY_NAME_PHONE_STEALER_4'),
('CIVILIZATION_TRENT_PHONE_STEALER','TXT_KEY_SPY_NAME_PHONE_STEALER_5'),
('CIVILIZATION_TRENT_PHONE_STEALER','TXT_KEY_SPY_NAME_PHONE_STEALER_6'),
('CIVILIZATION_TRENT_PHONE_STEALER','TXT_KEY_SPY_NAME_PHONE_STEALER_7'),
('CIVILIZATION_TRENT_PHONE_STEALER','TXT_KEY_SPY_NAME_PHONE_STEALER_8'),
('CIVILIZATION_TRENT_PHONE_STEALER','TXT_KEY_SPY_NAME_PHONE_STEALER_9');
INSERT INTO Language_en_US (Tag,Text) VALUES
('TXT_KEY_SPY_NAME_PHONE_STEALER_0','Missed Call'),
('TXT_KEY_SPY_NAME_PHONE_STEALER_1','Unknown Number'),
('TXT_KEY_SPY_NAME_PHONE_STEALER_2','No Caller ID'),
('TXT_KEY_SPY_NAME_PHONE_STEALER_3','AirDrop'),
('TXT_KEY_SPY_NAME_PHONE_STEALER_4','Charger'),
('TXT_KEY_SPY_NAME_PHONE_STEALER_5','Hotspot'),
('TXT_KEY_SPY_NAME_PHONE_STEALER_6','Voicemail'),
('TXT_KEY_SPY_NAME_PHONE_STEALER_7','Bluetooth'),
('TXT_KEY_SPY_NAME_PHONE_STEALER_8','Passcode'),
('TXT_KEY_SPY_NAME_PHONE_STEALER_9','Find My Phone');
